;Tempest (Atari, 1981) - hardware map, RAM variables and equates for
;tempest_program_rom.asm (rev 3).
;Names are Atari's identifiers from ALCOMN.MAC and the program modules
;(MAC65 symbols are significant to 6 characters, so a longer spelling such as
;QDSTATE is the same symbol as QDSTAT; '.' -> '_' and '$' -> 'S_').  A name the
;source defines with two different values keeps the name for the main one;
;ROM/RAM labels among the others get an _ADDR suffix.
;Descriptions are Atari's comments on the definitions (upper case) and, for the
;hardware, bit notes from ALCOMN.MAC and the AAE driver tempest.cpp.
;Generated by disasm/emit_defines.py; every symbol the program listing uses is here.

;----------------------------------[ Memory map ]----------------------------------
.alias ZeroPageRam      $00      ;Through $00FF. Control, work, player and display variables.
.alias PageOneRam       $0100    ;Through $01FF. Game variables; the 6502 stack grows down from $01FF (the IRQ requires SP >= $D0).
.alias GameRam          $0200    ;Through $07FF. Object tables, explosions, enemy lines, high scores.
.alias ColorRam         $0800    ;Through $080F. 16 colour entries, 4 bits active low: b0 red-low, b1 red, b2 blue, b3 green.
.alias VectorRam        $2000    ;Through $2FFF. AVG display lists (sub-buffers, see Vector RAM below).
.alias VectorRom        $3000    ;Through $3FFF. Characters and pictures (tempest_vector_rom.asm).
.alias AuxBoardIo       $6000    ;EAROM, Mathbox, two POKEYs, LED/flip latch (HARDWA).
.alias ProgramRom       $9000    ;Through $DFFF (tempest_program_rom.asm); vectors at $DFFA.
.alias RomMirror        $E000    ;Through $FFFF. Mirror of the top program ROM; the 6502 reads its vectors here.

;----------------------------------[ Hardware registers ]----------------------------------
.alias COLPORT          $0800    ;COLOR RAM. Colour RAM $0800-$080F (write): 16 entries, 4 bits active low (b0 red-low, b1 red, b2 blue, b3 green).
.alias IN1              $0C00    ;INPUT BYTE 1. Read: b0 right coin, b1 centre coin, b2 left coin, b3 slam, b4 self test, b5 diag step, b6 VG HALT (1 = done), b7 3 kHz clock.
.alias INOP0            $0D00    ;OPTION SWITCH 0. Read: option switches N13 (coinage).
.alias INOP1            $0E00    ;OPTION SWITCH 1. Read: option switches L12 (minimum credits, language, bonus life, lives).
.alias OUT0             $4000    ;OUTPUT BYTE 0. Write: b0 right coin counter, b1 centre, b2 left, b3 invert X (flip), b4 invert Y.
.alias VGSTART          $4800    ;VG START. Write: start the AVG at vector RAM $2000.
.alias WTCHDG           $5000    ;WATCH DOG CLEAR. Write: watchdog clear (the IRQ does it only while the software watchdog is happy).
.alias INTACK           $5000    ;Same address as WTCHDG: the write also acknowledges the IRQ.
.alias VGSTOP           $5800    ;VG RESET. Write: reset (halt) the AVG.
.alias HARDWA           $6000    ;AUX BOARD IO BASE ADDRESS. Auxiliary board I/O base.
.alias EADAL            $6000    ;EAROM WRITE BASE ADDRESS. Write $6000-$603F: EAROM address = offset, data = value latched for the next write.
.alias EACTL            $6040    ;EAROM CONTROL. Write: EAROM control (EACK clock, EAC2, EAC1 inverted, EACE chip select).
.alias MSTAT            $6040    ;STATUS. Read: Mathbox status, D7 = 1 while busy.
.alias EAIN             $6050    ;EAROM READ PORT. Read: EAROM data.
.alias MYLOW            $6060    ;READ LOW. Read: Mathbox result low byte.
.alias MYHIGH           $6070    ;READ HIGH. Read: Mathbox result high byte.
.alias MBSTAR           $6080    ;START (SIGNS ANALYSIS). Write $6080-$609F: Mathbox register load / function start (MAL..MDYPL below).
.alias MAL              $6080    ;Mathbox register A low byte (offset 0, write). Zeroed by INIMAT as an unused register
.alias MAH              $6081    ;Mathbox register A high byte (offset 1, write). Zeroed by INIMAT as an unused register
.alias MBL              $6082    ;Mathbox register B low byte (offset 2, write). Projection loads the inverse-scale multiplicand here
.alias MBH              $6083    ;Mathbox register B high byte (offset 3, write). Zeroed by INIMAT
.alias MEL              $6084    ;Mathbox register E low byte (offset 4, write). Zeroed by INIMAT as an unused register
.alias MEH              $6085    ;Mathbox register E high byte (offset 5, write). Zeroed by INIMAT as an unused register
.alias MFL              $6086    ;Mathbox register F low byte (offset 6, write). Zeroed by INIMAT as an unused register
.alias MFH              $6087    ;Mathbox register F high byte (offset 7, write). Zeroed by INIMAT as an unused register
.alias MXL              $6088    ;Mathbox register X low byte (offset 8, write). Projection loads abs(point - eye) X or Z delta here
.alias MXH              $6089    ;Mathbox register X high byte (offset 9, write). Zeroed by INIMAT
.alias MNL              $608C    ;Mathbox N (offset $0C): number of quotient bits. INIMAT sets $0F, CASCAL $18 for a fraction, READMB $10
.alias MZLL             $608D    ;Mathbox dividend Z byte 0 (offset $0D, lowest of 32 bits). Zeroed by INIMAT, set by self-test divides
.alias MZLH             $608E    ;Mathbox dividend Z byte 1 (offset $0E). WORSCR loads the abs Z/X deltas here, CASCAL loads YDEUNI
.alias MZHL             $608F    ;Mathbox dividend Z byte 2 (offset $0F). Zeroed by INIMAT, set by READMB
.alias MZHH             $6090    ;Mathbox dividend Z byte 3 (offset $10, highest of 32 bits). Zeroed by INIMAT, set by READMB
.alias SYM              $6092    ;Mathbox offset $12: any write starts the Y' multiply, output (x-e)b+(y-f)a. Starts projection multiply
.alias MSZXD            $6094    ;Mathbox offset $14: any write starts the Z/X' divide. Used by WORSCR, CASCAL and READMB
.alias MXPL             $6095    ;Mathbox X' (divisor) low byte (offset $15, write). Point depth minus eye Y (PYL-EYL)
.alias MXPH             $6096    ;Mathbox X' (divisor) high byte (offset $16, write)
.alias MDYPL            $6098    ;Mathbox offset $18: any write puts Y' low 16 bits on the output. Written after each multiply completes
.alias POKEY            $60C0    ;POKEY 1 ($60C0-$60CF): sound channels 1-4, spinner and cocktail input.
.alias AUDF1            $60C0    ;POKEY 1 AUDF1 ($60C0): channel 1 frequency. Base of the AUDF/AUDC pairs for sound channels 1-4 (X-indexed)
.alias AUDC1            $60C1    ;POKEY 1 AUDC1 ($60C1): channel 1 control (distortion and volume). AUDC1+2n for channels 2-4
.alias AUDCTL           $60C8    ;POKEY 1 AUDCTL ($60C8, write): audio control, set to AUDCV by INISOU. Same address as ALLPOT
.alias ALLPOT           $60C8    ;POKEY 1 read: b0-b3 spinner (4-bit position), b4 cocktail. (Write: AUDCTL.)
.alias RANDOM           $60CA    ;POKEY 1 read: random number (also used by the POKEY protection checks).
.alias POTGO            $60CB    ;POKEY 1 write: start pot scan.
.alias SKCTL            $60CF    ;POKEY 1 serial/keyboard control.
.alias POKEY2           $60D0    ;POKEY 2 ($60D0-$60DF): sound channels 5-8 and buttons.
.alias AUDF2            $60D0    ;POKEY 2 AUDF1 ($60D0): frequency of sound channel 5. Base of the AUDF/AUDC pairs for channels 5-8
.alias AUDC2            $60D1    ;POKEY 2 AUDC1 ($60D1): control of sound channel 5. Written only by the self-test sound check
.alias AUD2CTL          $60D8    ;POKEY 2 AUDCTL ($60D8, write): audio control, set to AUDCV2 by INISOU (source spelling AUD2CT)
.alias ALLPO2           $60D8    ;POKEY 2 read: b0-b1 difficulty, b2 rating, b3 superzapper, b4 fire, b5 start 1, b6 start 2. (Write: AUD2CTL.)
.alias RANDO2           $60DA    ;POKEY 2 read: random number.
.alias POTGO2           $60DB    ;POKEY 2 write: start pot scan.
.alias SKCTL2           $60DF    ;POKEY 2 serial/keyboard control.
.alias OUTANK           $60E0    ;OUTPUT BYTE 1. Write: b0 LED 2 (MLED2), b1 LED 1 (MLED1), b2 flip (MFLIP); LEDs active low.

;----------------------------------[ Zero page variables ]----------------------------------
.alias QSTATE           $00      ;CONTAINS CODE FOR STATE ROUTINE (INDEX INTO ROUTAD)
.alias QDSTATE          $01      ;DISPLAY STATE
.alias QNXTSTA          $02      ;NEXT STATE CODE TO EXECUTE AFTER PAUSE
.alias QFRAME           $03      ;FRAME COUNTER (WRAPS AT FF)
.alias QTMPAUS          $04      ;PAUSE TIMER (IN SECOND UNITS)
.alias QSTATUS          $05      ;STATUS FLAGS
.alias S_S_CRDT         $06      ;# OF CREDITS
.alias S_INTCT          $07      ;INTERRUPT COUNT
.alias S_TEST           $08      ;$TEST: self-test switch byte, same address as $COINA (copy of IN1). Never referenced by name
.alias S_LAM            $08      ;$LAM: slam switch byte for COIN65, same address as $COINA (IN1 copy). The coin routine tests the slam bit
.alias S_COINA          $08      ;COIN MECHS
.alias S_CMODE          $09      ;$CMODE: coin option switches for COIN65, same address as OPTIN1. INILIT stores INOP0 EOR 2 here
.alias OPTIN1           $09      ;OPTIONS
.alias OPTIN2           $0A      ;Copy of option switches INOP1: b0 2-game minimum, b1-b2 language, b3-b5 bonus life, b6-b7 lives
.alias TSLAMR           $0B      ;SLAM SOUND TIMER
.alias S_LMTIM          $0C      ;SLAM INDICATION
.alias S_CNSTT          $0D      ;$CNSTT: coin status/detection timers, one byte per coin mech (3, MECHS). Used by COIN65
.alias S_PSTSL          $10      ;$PSTSL: post-coin slam timers, one byte per coin mech (3). A slam in this window cancels the coin
.alias S_CCTIM          $13      ;$CCTIM: pulse timers for the 3 electro-mechanical coin counters (negative = on). IRQ copies to OUT0
.alias S_BCCNT          $16      ;$BCCNT: count of coins towards a bonus coin (COIN65). Cleared at power-on and game start
.alias S_CNCT           $17      ;$CNCT: unit-coin count not yet making a credit. Non-zero shows the 1/2 picture after the credits
.alias S_BC             $18      ;$BC: bonus coins accrued (COIN65). Cleared at power-on and game start
.alias COLRAM           $19      ;COLOR RAM
.alias TEMP0            $29      ;General scratch byte, first of the work variables TEMP0-TEMP4
.alias TEMP1            $2A      ;General scratch byte, second work variable (same address as TEMPL)
.alias TEMPL            $2A      ;Alternate name for TEMP1 (same address). Not referenced by name in the program
.alias TEMP2            $2B      ;General scratch byte, third work variable
.alias TEMP3            $2C      ;General scratch byte, fourth work variable
.alias TEMP4            $2D      ;General scratch byte, fifth work variable
.alias TEMPX            $2E      ;Scratch byte, often a point X coordinate (world or screen). Also mathbox self-test divisor low
.alias TEMPY            $2F      ;Scratch byte, often a point Y (depth) coordinate. Also mathbox self-test divisor high
.alias TEMPZ            $30      ;Scratch byte, point Z coordinate (right point in the line drawing setup)
.alias MTEMP            $31      ;MACRO USE ONLY
.alias SAVEX            $35      ;Scratch byte for saving the X register (loop index) across calls
.alias SAVEY            $36      ;Scratch byte for saving the Y register (loop index) across calls
.alias INDEX1           $37      ;General loop index/counter, first of INDEX1-INDEX4
.alias INDEX2           $38      ;General loop index/counter, second of INDEX1-INDEX4
.alias INDEX3           $39      ;Loop index/counter, third of INDEX1-INDEX4 (score display, self-test timer)
.alias INDEX4           $3A      ;Loop index/counter, fourth of INDEX1-INDEX4 (score display)
.alias INDYLO           $3B      ;USE FOR INDIRECT Y
.alias INDYHI           $3C      ;High byte of the INDYLO indirect (zp),Y pointer
.alias PLAYUP           $3D      ;PLAYER UP (0=LEFT, 1=RIGHT)
.alias NUMPLA           $3E      ;# OF PLAYERS (-1)
.alias NEWPLA           $3F      ;# OF NEXT PLAYER (FROM END WAVE TO NEW WAVE)
.alias LSCORL           $40      ;SCORE ARRAY
.alias LSCORM           $41      ;(TRIPLE PRECISION BCD)
.alias LSCORH           $42      ;Player 1 (left) score, high byte of the 3-byte BCD score LSCORL-LSCORH
.alias RSCORL           $43      ;Player 2 (right) score, low byte of the 3-byte BCD score
.alias RSCORM           $44      ;Player 2 (right) score, middle byte of the 3-byte BCD score
.alias RSCORH           $45      ;Player 2 (right) score, high byte of the 3-byte BCD score
.alias WAVEN1           $46      ;# OF ENEMY WAVE WHICH PLAYER IS BATTLING -1
.alias WAVEN2           $47      ;Player 2 wave number -1 (second slot of WAVEN1, accessed as WAVEN1,X)
.alias LIVES1           $48      ;# OF BASES PLAYER HAS LEFT
.alias LIVES2           $49      ;Player 2 bases left (second slot of LIVES1). Cleared for a one-player game
.alias INPUT            $4A      ;ROUGH INPUT (0=ON)
.alias DBSW             $4C      ;LAST ROUGH INPUT (0=ON)
.alias SWSTRT           $4D      ;Alternate name for SWSTAT (debounced switches, 0 = on). Read to test the start buttons
.alias SWSTAT           $4D      ;DEBOUNCED INPUT (0=ON)
.alias SWFINA           $4E      ;LATCHED INPUT (1=ON)(CLEARED BY GAME)
.alias SWRELE           $4F      ;OLD SWSTAT READING
.alias TBHD             $50      ;TRACK BALL VARIABLES
.alias CURSPO           $51      ;Cursor position between well lines (fine position, 3 bits used for the picture). Spinner input for initials
.alias OTB              $52      ;Previous 4-bit spinner reading from ALLPOT. The difference is added to TBHD each IRQ
.alias FRTIMR           $53      ;VG FRAME DISPLAY TIMER
.alias BUFRDY           $54      ;BUFFER STATUS (0-DISPLAY IT, <>0:BUILD IT)
.alias OBJIND           $55      ;INDEX INTO OBJECT ARRAYS (OCNT....)
.alias PXL              $56      ;TEMP STORAGE FOR POINT'S COORDINATES
.alias PYL              $57      ;(WORLD)
.alias PZL              $58      ;Z coordinate of the point being projected (world), with PXL and PYL
.alias LINSCA           $59      ;LINEAR SCALE (W3DSUP)
.alias BINSCA           $5A      ;BINARY SCALE (W3DSUP)
.alias EYH              $5B      ;EYE POSITION (SIGNED) HI BYTE
.alias EYLL             $5C      ;EYE POSITION (FRACTIONAL)
.alias EYLDES           $5D      ;EYE DESTINATION Y
.alias EXL              $5E      ;LOCATION OF EYE (WORLD COORD)
.alias EYL              $5F      ;Eye (camera) Y position in world coordinates (depth), low byte. EYH high, EYLL fraction
.alias EZL              $60      ;Eye (camera) Z position in world coordinates
.alias SXL              $61      ;TEMP STORAGE FOR POINT'S COORD
.alias SXH              $62      ;(SCREEN)
.alias SZL              $63      ;Projected screen Z (vertical) coordinate of the point, low byte (SXL/SXH is screen X)
.alias SZH              $64      ;Projected screen Z (vertical) coordinate of the point, high byte
.alias EYEFAC           $65      ;EYE SCREEN DISTANCE
.alias XADJL            $66      ;Screen X vanishing point, 2 bytes, added to projected X (0 = screen centre). ZADJL is the Z pair
.alias ZADJL            $68      ;SCREEN Z VANISH PT
.alias CURNTX           $6A      ;CURRENT BEAM POSITION
.alias CURNTY           $6C      ;Current beam position, screen vertical coordinate, 2 bytes (pairs with CURNTX)
.alias XCOMP            $6E      ;X COMPONENT FOR VECTOR DELTA
.alias YCOMP            $70      ;Vertical (screen Z) component of the vector delta, 2 bytes at XCOMP+2
.alias VGSIZE           $72      ;SCALING SIZE
.alias VGBRIT           $73      ;VECTOR BRIGHTNESS
.alias VGLIST           $74      ;VECTOR LIST POINTER
.alias SVGLIST          $76      ;Saved VGLIST: second display list pointer, exchanged with VGLIST by SWAPVG (mainline/subroutine)
.alias X0L              $78      ;USED WITHIN ONELIN IN ALDISP TO
.alias BFACTR           $78      ;USED IN SCAPIC - BINARY PART OF SCALE FACTOR
.alias X1L              $79      ;STORE UNIT VECTORS X 0>7 (X AND Z)
.alias SCFL             $79      ;USED IN SCAPIC - SCALE FACTOR
.alias X2L              $7A      ;ONELIN unit-vector multiples: 2 x X1L, low byte (XnL/XnH = n times the X unit vector)
.alias X3L              $7B      ;ONELIN unit-vector multiples: 3 x X1L, low byte
.alias LEFSID           $7B      ;REQUEST RATE DISPLAY LEFT SIDE
.alias X4L              $7C      ;ONELIN unit-vector multiples: 4 x X1L, low byte
.alias RITSID           $7C      ;RRD-RIGHT SIDE
.alias X5L              $7D      ;ONELIN unit-vector multiples: 5 x X1L, low byte
.alias X6L              $7E      ;ONELIN unit-vector multiples: 6 x X1L, low byte
.alias X7L              $7F      ;ONELIN unit-vector multiples: 7 x X1L, low byte
.alias X0H              $80      ;ONELIN unit-vector multiples: 0 x X1L, high byte (zeroed by INIMAT, read indexed as X0H,Y)
.alias X1H              $81      ;ONELIN unit-vector multiples: 1 x X1L, high byte (zeroed by INIMAT)
.alias X2H              $82      ;ONELIN unit-vector multiples: 2 x X1L, high byte
.alias X3H              $83      ;ONELIN unit-vector multiples: 3 x X1L, high byte
.alias X4H              $84      ;ONELIN unit-vector multiples: 4 x X1L, high byte
.alias X5H              $85      ;ONELIN unit-vector multiples: 5 x X1L, high byte
.alias X6H              $86      ;ONELIN unit-vector multiples: 6 x X1L, high byte
.alias X7H              $87      ;ONELIN unit-vector multiples: 7 x X1L, high byte
.alias Z0L              $88      ;ONELIN unit-vector multiples: 0 x Z1L, low byte (zeroed by INIMAT, read indexed as Z0L,X/Y)
.alias Z1L              $89      ;ONELIN Z unit vector: abs(screen Z delta) clamped to one byte, low byte (ZnL/ZnH = n x Z1L)
.alias Z2L              $8A      ;ONELIN unit-vector multiples: 2 x Z1L, low byte
.alias Z3L              $8B      ;ONELIN unit-vector multiples: 3 x Z1L, low byte
.alias Z4L              $8C      ;ONELIN unit-vector multiples: 4 x Z1L, low byte
.alias Z5L              $8D      ;ONELIN unit-vector multiples: 5 x Z1L, low byte
.alias Z6L              $8E      ;ONELIN unit-vector multiples: 6 x Z1L, low byte
.alias Z7L              $8F      ;ONELIN unit-vector multiples: 7 x Z1L, low byte
.alias Z0H              $90      ;ONELIN unit-vector multiples: 0 x Z1L, high byte (zeroed by INIMAT)
.alias Z1H              $91      ;ONELIN unit-vector multiples: 1 x Z1L, high byte (zeroed by INIMAT)
.alias Z2H              $92      ;ONELIN unit-vector multiples: 2 x Z1L, high byte
.alias Z3H              $93      ;ONELIN unit-vector multiples: 3 x Z1L, high byte
.alias Z4H              $94      ;ONELIN unit-vector multiples: 4 x Z1L, high byte
.alias Z5H              $95      ;ONELIN unit-vector multiples: 5 x Z1L, high byte
.alias Z6H              $96      ;ONELIN unit-vector multiples: 6 x Z1L, high byte
.alias Z7H              $97      ;ONELIN unit-vector multiples: 7 x Z1L, high byte
.alias INTENS           $98      ;OBJECT INTENSITY (D7-D5)
.alias SUBCOU           $99      ;POINT COUNTER
.alias UNITXL           $9A      ;UNIT VECTORS
.alias UNITXH           $9B      ;High byte (sign) of the screen X delta between line endpoints in ONELIN. Sign for the unit vector
.alias UNITZL           $9C      ;Unit vector Z low byte slot. Allocated but never referenced (Z1L is used instead)
.alias UNITZH           $9D      ;High byte (sign) of the screen Z delta between line endpoints in ONELIN. Sign for the unit vector
.alias COLOR            $9E      ;Colour of the object being drawn, input to the picture and line routines
.alias CURWAV           $9F      ;CURRENT WAVE
.alias YDEUNI           $A0      ;Y DELTA FOR UNIT SCALE
.alias TNKOUT           $A1      ;START LEDS, ETC. FOR DUTANK
.alias TCMFLG           $A2      ;2 GAME MIN FLAG (80=NOT 2 YET)
.alias NEWAIT           $A3      ;Allocated in ALCOMN (display variables). Never referenced by the program
.alias OFRTIM           $A4      ;Allocated in ALCOMN (display variables). Never referenced by the program
.alias OCURSL           $A5      ;OLD CURSOR POSITION (LINE #)
.alias ESHCOU           $A6      ;ENEMY SOT COUNT
.alias CHACHA           $A7      ;CHARGE CHARGE DELTA
.alias CHAINV           $A8      ;CHARGE INVADER DELTA
.alias VGY              $A9      ;INDEX INTO VGLIST
.alias OLDLLO           $AA      ;OLD ENEMY LINE BUFFER START ADDRESS
.alias OLDLHI           $AB      ;Old enemy line buffer start address, high byte (OLDLLO is the low byte)
.alias LITRAL           $AC      ;LANGUAGE TABLE
.alias ZPNLOC           $AE      ;USED BY DIGITS
.alias ZPOFFS           $AF      ;USED BY DIGITS
.alias RUNGVG           $B0      ;RUNG VG PTR.
.alias PUCHDE           $B2      ;PULSAR CHASE DELAY (# FRAMES BEFORE FLIP)
.alias WTTFRA           $B3      ;# OF FLIP SECTIONS TO TAKE/FRAME FOR TOP FLIPPERS
.alias TOUT0            $B4      ;SCREEN FLIP STATUS FOR IO
.alias QT1              $B5      ;SECURITY
.alias SECUVG           $B6      ;SECURITY PTR.
.alias EASRCE           $BD      ;RAM POINTER
.alias SINDEX           $BF      ;Sound channel being started by SNDON ($FF when none). MODSND skips that channel meanwhile
.alias POINT            $C0      ;POINTER OFFSET INTO DATA TABLES(IF 0, CHANNEL NOT ACTIVE)
.alias CURRENT          $D0      ;OUTPUT VALUE
.alias FRAMES           $E0      ;FRAMES UNTIL NEXT CHANGE
.alias COUNT            $F0      ;COUNT OF TOTAL CHANGES

;----------------------------------[ Stack page ]----------------------------------
.alias NGAMES           $0100    ;# GAMES FOR RANKING
.alias NPLAYR           $0101    ;# PLAYERS
.alias BONUS            $0102    ;BONUS CODE FOR STARTING AT ADVANCED WAVE
.alias CURSVL           $0104    ;CURSOR ACCELERATION DOWN WELL
.alias CURSVH           $0105    ;Cursor acceleration down the well, high byte (CURSVL is the low byte)
.alias CURMOD           $0106    ;CURSOR MODE (-:DROPPING)
.alias CURSYL           $0107    ;CURSOR POSITION (FRACTIONAL)
.alias INMCOU           $0108    ;# OF INVADERS ON LINES
.alias INCCOU           $0109    ;# OF INVADERS CHASING CURSOR
.alias EXICAM           $010A    ;INVADER CAN EXIT FLAG
.alias CAMPC            $010B    ;INVADER CAM PC
.alias CAMSTA           $010C    ;CAM STATUS
.alias BOOMFL           $010D    ;BOOM ACTIVE FLAG (0=NOT ACTIVE)
.alias BOOMTI           $010E    ;BOOM TIMER (1/5 SECONDS)
.alias LEVELY           $010F    ;Well off-screen flags, 2 bytes: +0 top of well, +1 bottom of well (non-zero = off screen). Set by BLDWEL
.alias WELTYP           $0111    ;WELL TYPE (0=CLOSED,-1=OPEN)
.alias WELLID           $0112    ;WELL CODE
.alias ROTFLG           $0113    ;MSB OF BUILT SUBR BUFFER (IF 0 THEN NOT READY)
.alias ROTDIS           $0114    ;BUILD WELL REQUEST (NOT 0)
.alias PLAGRO           $0115    ;STAR FIELD STATUS
.alias EXPCOU           $0116    ;# OF EXPLOSIONS
.alias COCTAL           $0117    ;COCKTAIL FLAG
.alias WCHARIN          $0118    ;INVADER CHARGE INC/FRAME
.alias WCHARFR          $0119    ;INVADER CHARGE FREQUENCY (FIRE
.alias WCHAMX           $011A    ;MAX # OF INVADER CHARGES ON GIRD-1
.alias QT6              $011B    ;Security: checksum of the ATARI copyright display list in attract (0 = intact). Non-zero corrupts RAM later
.alias WINVMX           $011C    ;MAX # OF INVADERS-1
.alias WINVJM           $011D    ;INVAER JUMP FREQ (JUMP IF
.alias WNYMMX           $011E    ;# OF NYMPHS
.alias QT5              $011F    ;Security: POKEY random-number check result (0 = OK). If non-zero with a high score, ZQPONS corrupts RAM
.alias WCHARL           $0120    ;FRACTION CHARGE INC
.alias ZADEST           $0121    ;ZADJL DEST.
.alias ELICNT           $0123    ;ENEMY LINE COUNTER (D7=1:WARNING REQUEST)
.alias BOFLASH          $0124    ;BONUS FLASH TIMER
.alias SUZTIM           $0125    ;SUPERZAP TIMER
.alias HIWAVE           $0126    ;HIGHEST WAVE REACHED IN LAST GAME
.alias HIRATE           $0127    ;HIGHEST LEVEL-1/2 ALLOWED IN RATE TABLE
.alias INTIME           $0128    ;TIME SNCE LAST GAME (13 SECOND UNITS)
.alias WFLMIN           $0129    ;MINIMUM # OF TYPE ON WELL
.alias WPUMIN           $012A    ;Minimum number of pulsars on the well this wave (slot 1 of WFLMIN-WFUMIN, from WTABLE)
.alias WTAMIN           $012B    ;Minimum number of tankers on the well this wave (slot 2 of WFLMIN-WFUMIN, from WTABLE)
.alias WSPMIN           $012C    ;Minimum number of spinners (type 3) on the well this wave (slot 3 of WFLMIN-WFUMIN, from WTABLE)
.alias WFUMIN           $012D    ;Minimum number of fuseballs on the well this wave (slot 4 of WFLMIN-WFUMIN, from WTABLE)
.alias WFLMAX           $012E    ;MAX # OF TYPE ON WELL
.alias WPUMAX           $012F    ;Maximum number of pulsars on the well this wave (slot 1 of WFLMAX-WFUMAX, from WTABLE)
.alias WTAMAX           $0130    ;Maximum number of tankers on the well this wave (slot 2 of WFLMAX-WFUMAX, from WTABLE)
.alias WSPMAX           $0131    ;Maximum number of spinners (type 3) on the well this wave (slot 3 of WFLMAX-WFUMAX, from WTABLE)
.alias WFUMAX           $0132    ;Maximum number of fuseballs on the well this wave (slot 4 of WFLMAX-WFUMAX, from WTABLE)
.alias SPARE3           $0133    ;VG halted flag (2 bytes): IRQ increments it when the AVG halts. DISPLAY waits for it, INIDSP clears it
.alias CHACOU           $0135    ;# OF CHARGES
.alias WTFMAX           $0136    ;TANKER + FLIPPER MAX
.alias SPLINE           $0139    ;LINEAR SCALE VALUABLE
.alias SPBINA           $013A    ;BINARY SCALE VARIABLE
.alias SPXIND           $013B    ;INDEX
.alias SPFTIM           $013C    ;TIMER
.alias OPFLIP           $013D    ;OPENINGS FOR EACH TYPE
.alias OPPULS           $013E    ;Openings for pulsars (slot 1 of OPFLIP-OPFUSE), computed by NYMCHA. Accessed only as OPFLIP,X
.alias OPTANK           $013F    ;Openings for tankers (slot 2 of OPFLIP-OPFUSE). Smart launch picks a tanker for a long enemy line
.alias OPSPIN           $0140    ;Openings for spinners (slot 3 of OPFLIP-OPFUSE). Also the line loop counter in ASTRAL
.alias OPFUSE           $0141    ;Openings for fuseballs (slot 4 of OPFLIP-OPFUSE). Accessed only as OPFLIP,X
.alias FLIPCO           $0142    ;Count of active flippers (slot 0 of the per-type counts FLIPCO-FUSECO, indexed by invader type)
.alias PULSCO           $0143    ;COUNT OF EACH TYPE
.alias TANKCO           $0144    ;Count of active tankers (slot 2 of FLIPCO-FUSECO). Cleared by INIINV
.alias SPINCO           $0145    ;Count of active spinners (slot 3 of FLIPCO-FUSECO). Cleared by INIINV
.alias FUSECO           $0146    ;Count of active fuseballs (slot 4 of FLIPCO-FUSECO). Cleared by INIINV
.alias PULTIM           $0147    ;PULSE TIMER INCREMENT
.alias PULSON           $0148    ;PULSE STATUS (MINUS=OFF)
.alias WTACAR           $0149    ;TANK CONTENTS (4 POSSIBILITIES)
.alias NEARY            $014D    ;VORTEX LOGO
.alias FARY             $014E    ;Vortex logo rainbow far point depth (NEARY is the near point)
.alias NEOFLI           $014F    ;NYMPHS OFF LIMIT ZONE FLAGS
.alias OLOFLI           $0150    ;Nymph off-limit line flags of the last frame (copy of NEOFLI). Written at L991F, never read
.alias ENSIZE           $0151    ;COLLISION RANGE FOR EACH INVADER TYPE
.alias BLIFIN           $0156    ;BONUS LIFE INTERVAL
.alias PULPOT           $0157    ;HEIGHT AT WHICH PULEARS BECOME POTENT
.alias LVSGAM           $0158    ;LIVES/GAME
.alias WFUSCH           $0159    ;FUSE CHASE PLAYER FLAG (D7 FOR TOP;D6 FOR TUBE)
.alias NWTELI           $015A    ;NEW WAVE ENEMY LINE HEIGHT
.alias NWNYMC           $015B    ;NEW WAVE NYMPH COUNT
.alias WPULCAM          $015C    ;PULSAR CAM FOR WAVE
.alias WFLICAM          $015D    ;FLIPPER CAM FOR USAVE
.alias TYPCOD           $015E    ;Type code of the current wave parameter record (0 = end), dispatch index for DOTYPE/DONEXT
.alias WFUFRQ           $015F    ;FUSE LANE CHANGE PCNT (OF 256.)
.alias WINVIL           $0160    ;INVADER SPEED (FRAC) FOR EACH TYPE
.alias WFUSIL           $0164    ;Fuseball speed, fraction (slot 4 of WINVIL). Set to twice the invader speed
.alias WINVIN           $0165    ;INVADER SPEED (INT)
.alias WFUSIH           $0169    ;Fuseball speed, integer (slot 4 of WINVIN). Set to twice the invader speed
.alias OPTIN3           $016A    ;OPTION SWITCH 3 (BANK OF 4)
.alias PSCALE           $016B    ;PAUSE SEALER
.alias QT2              $016C    ;SECURITY
.alias WPULFI           $016D    ;PULSAR FIRE FLAG
.alias SECUVY           $016E    ;SECURITY COUNTER
.alias EAZFLG           $01C6    ;EA ROM ZERO FLAG (NOT 0=ZERO EAROM)
.alias EAREQU           $01C7    ;EA ROM ACCESS REQUEST
.alias EARWRQ           $01C8    ;EA ROM ACCESS TYPE (MATCHES EAREQU)
.alias EABAD            $01C9    ;EA ROM ACCESS SUCCESS(0) FAIL(1) (MATCHES EAREQU)
.alias EAFLG            $01CA    ;D7=1=ERASE ;=0=R/W
.alias EABC             $01CB    ;BYTE INDEX INTO ADDRESS AT EASRCE
.alias EAX              $01CC    ;BYTE OFFSET INTO EAROM FOR NEXT ACCESS
.alias EACNT            $01CD    ;BYTE OFFSET INTO EAROM FOR LAST ACCESS
.alias EASEL            $01CE    ;INDEX CODE FOR CURRENT BATCH OPERATION
.alias EACS             $01CF    ;CHECKSUM

;----------------------------------[ Game RAM ]----------------------------------
.alias CURSL1           $0200    ;ONE END LINE #
.alias CURSL2           $0201    ;OTHER END LINE # (CCW TO CURSL1)
.alias CURSY            $0202    ;CURSOR DEPTH
.alias NYMPL            $0203    ;Nymph table (64 entries): well line number of each nymph. Particle arrays overlay this area
.alias PARLIX           $0203    ;FRACTIONAL POSITION
.alias PARLIY           $0223    ;Big Boom particle Y position, fraction (one byte per particle, overlays NYMPL)
.alias NYMPY            $0243    ;Nymph table (64 entries): depth of each nymph (0 = inactive). Reaching 0 converts it to an invader
.alias PARLIZ           $0243    ;Big Boom particle Z position, fraction (one byte per particle, overlays NYMPY)
.alias PARTIX           $0263    ;INTEGER POSITION (80=CENTER)
.alias INVAC1           $0283    ;INVADER STATUS BYTE 1
.alias PARTIY           $0283    ;Big Boom particle Y position, integer ($80 = centre, 0 = particle inactive)
.alias INVAC2           $028A    ;INVADER STATUS BYTE 2
.alias INVCAM           $0291    ;Invader CAM program counter, one byte per invader (NINVAD = 7)
.alias INVLOO           $0298    ;Invader CAM loop counter, one byte per invader (set by JSLOOP, counted down by JELOOP)
.alias INVAYL           $029F    ;Y POSITION (FRACTIONAL)
.alias PARTIZ           $02A3    ;Big Boom particle Z position, integer ($80 = centre)
.alias INVACT           $02A6    ;TIME SINCE LAST CHARGE LAUNCH
.alias CHARL1           $02AD    ;ONE END LINE #
.alias INVAL1           $02B9    ;LINE # FOR 1 LEG (INVADERS)
.alias CHARL2           $02C0    ;OTHER END LINE # (CCW TO CHARL1)
.alias PARLXV           $02C3    ;FRACTIONAL VELOCITY
.alias INVAL2           $02CC    ;LINE # FOR CCW LEG (JUMPS SEG.IF-)
.alias CHARY            $02D3    ;Y POSITION (0=INACTIVE)
.alias INVAY            $02DF    ;Y POSITION FOR LEGS (INVADERS)
.alias PARLYV           $02E3    ;Big Boom particle Y velocity, fraction (random at launch)
.alias CHARYL           $02E6    ;Y POSITION FRACTION
.alias CHARCO           $02F2    ;CHARGE COLLISION COUNTER
.alias EXPLOL           $02FA    ;EXPLOSION LINE # (CW LEG)
.alias EXPLOT           $0302    ;EXPLOSION TYPE
.alias PARLZV           $0303    ;Big Boom particle Z velocity, fraction (random at launch)
.alias EXPLOY           $030A    ;EXPLOSION DEPTH (WORLD Y)
.alias EXPLOS           $0312    ;EXPLOSION SEQUENCES
.alias LINSXH           $031A    ;NEAR PT.
.alias PARTXV           $0323    ;INTEGER VELOCITY (SIGNED)
.alias LINSXL           $032A    ;Well line near point screen X, low byte, one per line (LINSXH high)
.alias LINSZH           $033A    ;Well line near point screen Z, high byte, one per line
.alias PARTYV           $0343    ;Big Boom particle Y velocity, integer (signed)
.alias LINSZL           $034A    ;Well line near point screen Z, low byte, one per line
.alias LIFSXH           $035A    ;FAR PT.
.alias PARTZV           $0363    ;Big Boom particle Z velocity, integer (signed)
.alias LIFSXL           $036A    ;Well line far point screen X, low byte, one per line (LIFSXH high)
.alias LIFSZH           $037A    ;Well line far point screen Z, high byte, one per line
.alias LIFSZL           $038A    ;Well line far point screen Z, low byte, one per line
.alias LINSTA           $039A    ;ENEMY LINE STATUS (D7=1:NEW NEAR PT.;D6=1=SHATTERED)
.alias ACTIP            $03AA    ;ACTIVE PLAYER DATA
.alias SUZCNT           $03AA    ;SUPERZAPPER USE COUNTER
.alias NYMCOU           $03AB    ;# OF NYMPHS
.alias LINEY            $03AC    ;ENEMY LINE HEIGHTS
.alias SAVEP            $03BC    ;STANDBY PLAYER DATA
.alias SAVEND           $03CE    ;DUMMY
.alias LINEX            $03CE    ;Well line point X world coordinate, one per line (16), from the well shape tables
.alias LINEZ            $03DE    ;Well line point Z world coordinate, one per line (16), from the well shape tables
.alias LINANG           $03EE    ;INDEX=ANGLE FROM GRID LINE TO NEXT CCW LINE
.alias PLANEY           $03FE    ;STAR FIELD PLANES
.alias BOOKKS           $0406    ;BOOKKEEPING
.alias SECOUL           $0406    ;GAME UP TIMER
.alias SECOUM           $0407    ;Bookkeeping game up timer (seconds), middle byte. Counted by the IRQ
.alias SECOUH           $0408    ;Bookkeeping game up timer (seconds), high byte
.alias SECOPL           $0409    ;GAME PLAY TIMER
.alias SECOPM           $040A    ;Bookkeeping game play timer (seconds), middle byte. Counted while in game timer mode
.alias SECOPH           $040B    ;Bookkeeping game play timer (seconds), high byte
.alias NGAMIL           $040C    ;# OF GAMES
.alias NGAMIH           $040D    ;Bookkeeping count of 1-player games, high byte (NGAMIL low)
.alias NGAME0           $040E    ;Third byte of the 1-player games count. Saved in EAROM, never referenced by name
.alias NGAM2L           $040F    ;# OF 2 PLAYER GAMES
.alias NGAM2H           $0410    ;Bookkeeping count of 2-player games, high byte (NGAM2L low)
.alias NGAM20           $0411    ;Third byte of the 2-player games count. Saved in EAROM, never referenced by name
.alias BOOKKE           $0412    ;End of the bookkeeping block BOOKKS-BOOKKE saved to EAROM (BOOKKE-BOOKKS = its length)
.alias NGAVGL           $0412    ;ORIG GAME TIME
.alias NGAVGH           $0413    ;Average game time (play time / games) high byte, computed by the self-test bookkeeping page
.alias NGAVGZ           $0414    ;Third byte after NGAVGL/H. Only cleared (READMB stores 0 there)
.alias BUFACT           $0415    ;ACTIVE/AVAILABLE BUFFER
.alias SPOKST           $0425    ;SPOKE STATUS (PULEARS)
.alias LINEXM           $0435    ;HALF WAY BETWEEN LINES COORDINATES
.alias LINEZM           $0445    ;Z world coordinate of the point halfway between each well line and the next (LINEXM is X)
.alias QT3              $0455    ;SECURITY
.alias RANKS            $0600    ;RANK FOR ACH PLAYER(0=NO RANK)
.alias TBLIND           $0602    ;INDEX INTO INITIAL OF NEW INITIAL
.alias FLGNHI           $0603    ;FLAG FOR HIS SCORE FOUND
.alias ININDX           $0604    ;NEW INITIALS LEFT-1 COUNTER
.alias TIMHIS           $0605    ;TIMER UNTIL INITIAL ENTRY IS ABORTED
.alias INITAL           $0606    ;High score initials, 3 bytes per entry for the 8 high scores (top entry last). Top 3 kept in EAROM
.alias HRANKL           $061E    ;Score rank table (256 bytes): 41 2-byte then 58 3-byte BCD scores, lowest first. Low byte
.alias HRANKM           $061F    ;Score rank table, middle BCD byte of each entry (HRANKL+1)
.alias HRANKH           $0620    ;Score rank table, high BCD byte of each entry (HRANKL+2)
.alias HSCORL           $0706    ;High score table: last 8 entries of the rank table, 3-byte BCD, low bytes. Top score at +21
.alias HSCORM           $0707    ;High score table, middle BCD byte of each entry (HSCORL+1)
.alias HSCORH           $0708    ;High score table, high BCD byte of each entry (HSCORL+2)
.alias GAMOP1           $071E    ;GAME PLAY OPTIONS (SWITCH 1)
.alias GAMOP3           $071F    ;(SWITCH 3)
.alias QT4              $0720    ;SECURITY

;----------------------------------[ Vector RAM ]----------------------------------
.alias VECRAM           $2000    ;VECTOR RAM
.alias SWINFO           $2004    ;Info (scores, messages) sub-buffer switch: 2-byte JMPL in vector RAM pointing to BAINFO or BBINFO
.alias BAINFO           $2006    ;Info sub-buffer, area A (display list built here while area B is shown)
.alias BBINFO           $2104    ;Info sub-buffer, area B (display list built here while area A is shown)
.alias SWENEL           $2200    ;Enemy line (spikes) sub-buffer switch: JMPL pointing to BAENEL or BBENEL
.alias BAENEL           $2202    ;Enemy line sub-buffer, area A
.alias BBENEL           $2306    ;Enemy line sub-buffer, area B
.alias SWWELL           $240A    ;Well sub-buffer switch: JMPL pointing to BAWELL or BBWELL
.alias BAWELL           $240C    ;Well sub-buffer, area A
.alias BBWELL           $254E    ;Well sub-buffer, area B
.alias SWINVA           $2690    ;Invader sub-buffer switch: JMPL pointing to BAINVA or BBINVA
.alias BAINVA           $2692    ;Invader sub-buffer, area A
.alias BBINVA           $27C8    ;Invader sub-buffer, area B
.alias SWSHOT           $28FE    ;Shot (charges) sub-buffer switch: JMPL pointing to BASHOT or BBSHOT
.alias BASHOT           $2900    ;Shot sub-buffer, area A
.alias BBSHOT           $29AA    ;Shot sub-buffer, area B
.alias SWNYMP           $2A54    ;Nymph sub-buffer switch: JMPL pointing to BANYMP or BBNYMP
.alias BANYMP           $2A56    ;Nymph sub-buffer, area A
.alias BBNYMP           $2B96    ;Nymph sub-buffer, area B
.alias SWEXPL           $2CD6    ;Explosion sub-buffer switch: JMPL pointing to BAEXPL or BBEXPL
.alias BAEXPL           $2CD8    ;Explosion sub-buffer, area A
.alias BBEXPL           $2D4A    ;Explosion sub-buffer, area B
.alias SWCURS           $2DBC    ;Cursor (player) sub-buffer switch: JMPL pointing to BACURS or BBCURS
.alias BACURS           $2DBE    ;Cursor sub-buffer, area A
.alias BBCURS           $2DF0    ;Cursor sub-buffer, area B
.alias SWSTAR           $2E22    ;Star field sub-buffer switch: JMPL pointing to BASTAR or BBSTAR
.alias BASTAR           $2E24    ;Star field sub-buffer, area A
.alias BBSTAR           $2EA6    ;Star field sub-buffer, area B
.alias SCOBUF           $2F60    ;RAM copy of the score/lives/high score template SCORES at $2F60, updated in place
.alias SCLEVEL          $2FA6    ;Level number JSRLs inside SCOBUF (SCLEVL offset). Blanked in attract, set to the wave number
.alias SCALE            $2FFC    ;RAM scale instruction at $2FFC called by the shrapnel pictures. SHRSCA writes scale and RTSL

;----------------------------------[ Vector ROM ]----------------------------------
.alias CHAR_0           $30CA    ;Digit 0 character (source CHAR.0), same picture as the letter O (CHAR.O)
.alias CHAR_            $3168    ;Space character (source CHAR.): a blank 24-unit move then RTSL
.alias VGMSGA           $31E4    ;ADDRESS OF LETTER ROUTINES
.alias HALF             $325C    ;1/2 picture (digits 1 and 2 at scale 2), shown after the credits when a partial credit exists
.alias LIFEY            $326C    ;Player life picture with a yellow colour instruction first, then LIFE1. Used by the self-test lives display
.alias LIFE0            $327E    ;Vector ROM: blank life slot, beam advance only. The score template holds 6 JSRL LIFE0 per player (SCP1LI, SCP2LI)
.alias LSYMBL           $3284    ;Vector ROM: a JSRL LIFE1 word that UPSCLI ($A9A9) copies into the score template to show one life symbol
.alias LSYMB0           $3286    ;Vector ROM: a JSRL LIFE0 word that UPSCLI ($A9B2) copies into the score template for an empty life slot
.alias INTEST           $32B6    ;Vector ROM: self-test colour and intensity bars picture, drawn by SINTEN ($DB7E)
.alias HATCH            $330A    ;Vector ROM: self-test cross-hatch pattern followed by the alphabet, drawn by SHATCH ($DB84)
.alias CHEKER           $334E    ;Vector ROM: self-test grid of 15 horizontal and 11 vertical lines, drawn by SCHEKR ($DB78)
.alias HYSTER           $3456    ;Vector ROM: self-test hysteresis box picture, drawn by SHYSTE ($DBBD)
.alias EASING           $346E    ;Vector ROM: 'ERASING' message shown by the system display DSPSYS ($D87F) while the EAROM is being erased
.alias COCMSG           $3482    ;COCKTAIL GAME MESSAGE
.alias ROMRPI           $3492    ;Vector ROM: bad-ROM report frame (boundary, midline, text position) drawn by BADBOX ($DC7E) in self test
.alias BONDRY           $34A6    ;SCREEN BOUNDARY
.alias VORBOX           $34AA    ;Vector ROM: screen boundary rectangle entered after BONDRY's colour and scale. Used by BOXPRO logo box and SHYSTE
.alias EXPL1            $34C2    ;Vector ROM picture: explosion frame 1 of 4 (smallest, 16 spokes), PICLO offset $00 (PTEXP1)
.alias EXPL2            $34F8    ;Vector ROM picture: explosion frame 2 of 4, PICLO offset $02 (PTEXP1+2)
.alias EXPL3            $3522    ;Vector ROM picture: explosion frame 3 of 4, PICLO offset $04 (PTEXP1+4)
.alias EXPL4            $355A    ;Vector ROM picture: explosion frame 4 of 4 (largest), PICLO offset $06 (PTEXP1+6)
.alias DIARA2           $3594    ;Vector ROM picture: player shot, a diamond of dots of radius 2, PICLO offset $08 (PTCURS), drawn by DSPCHG
.alias STAR1            $3628    ;Vector ROM picture: warp star field frame 1 of 4, PICLO offset $0A (PTSTR1), selected by DSTARF
.alias STAR2            $36DE    ;Vector ROM picture: warp star field frame 2 of 4, PICLO offset $0C (PTSTR1+2)
.alias STAR3            $3780    ;Vector ROM picture: warp star field frame 3 of 4, PICLO offset $0E (PTSTR1+4)
.alias STAR4            $382A    ;Vector ROM picture: warp star field frame 4 of 4, PICLO offset $10 (PTSTR1+6)
.alias SPIRA1           $38CC    ;Vector ROM picture: green spiker (trailer) spiral frame 1 of 4, PICLO offset $12 (PTSPI1), chosen by TRAPIC
.alias SPIRA2           $38FA    ;Vector ROM picture: green spiker (trailer) spiral frame 2 of 4, PICLO offset $14 (PTSPI1+2)
.alias SPIRA3           $3928    ;Vector ROM picture: green spiker (trailer) spiral frame 3 of 4, PICLO offset $16 (PTSPI1+4)
.alias SPIRA4           $3956    ;Vector ROM picture: green spiker (trailer) spiral frame 4 of 4, PICLO offset $18 (PTSPI1+6)
.alias TANKP            $3984    ;TANKER OF PULSARS
.alias TANKF            $3996    ;TANKER OF FUSES
.alias TANKR            $39B0    ;Vector ROM picture: purple tanker carrying flippers, PICLO offset $1A (PTTANK), chosen via TANTAB
.alias SPARK1           $39F4    ;Vector ROM picture: yellow shot-hit sparkle frame 1 of 2, PICLO offset $1C (PTSPAR)
.alias SPARK2           $3A1A    ;Vector ROM picture: yellow shot-hit sparkle frame 2 of 2, PICLO offset $1E (PTSPAR+2)
.alias ESHOT1           $3A40    ;Vector ROM picture: enemy shot frame 1 of 4, PICLO offset $20 (PTESHO), animated by DSPCHG
.alias ESHOT2           $3A72    ;Vector ROM picture: enemy shot frame 2 of 4, PICLO offset $22 (PTESHO+2)
.alias ESHOT3           $3AA2    ;Vector ROM picture: enemy shot frame 3 of 4, PICLO offset $24 (PTESHO+4)
.alias ESHOT4           $3AD4    ;Vector ROM picture: enemy shot frame 4 of 4, PICLO offset $26 (PTESHO+6)
.alias SPLAT1           $3B04    ;Vector ROM picture: player-death splat, largest size (Atari TARGET SPLAT), PICLO offset $32
.alias SPLAT2           $3B08    ;Vector ROM picture: player-death splat size 2 of 6 (sets scale then JSRL SPLAT), PICLO offset $30
.alias SPLAT3           $3B0C    ;Vector ROM picture: player-death splat size 3 of 6, PICLO offsets $2E and $34
.alias SPLAT4           $3B10    ;Vector ROM picture: player-death splat size 4 of 6, PICLO offset $2C
.alias SPLAT5           $3B14    ;Vector ROM picture: player-death splat size 5 of 6, PICLO offsets $2A and $36
.alias SPLAT6           $3B18    ;Vector ROM picture: player-death splat, smallest (SMALL SPLAT), PICLO offsets $28 (PTSPLA) and $38
.alias SPLFU1           $3B84    ;Vector ROM picture: fuseball-kills-player explosion frame 1 of 7 (white star burst), PICLO offset $3C
.alias SPLFU2           $3B8A    ;Vector ROM picture: fuseball-kills-player explosion frame 2 of 7 (white), PICLO offset $3E
.alias SPLFU3           $3B90    ;Vector ROM picture: fuseball-kills-player explosion frame 3 of 7 (yellow), PICLO offset $40
.alias SPLFU4           $3B96    ;Vector ROM picture: fuseball-kills-player explosion frame 4 of 7 (yellow), PICLO offset $42
.alias SPLFU5           $3B9C    ;Vector ROM picture: fuseball-kills-player explosion frame 5 of 7 (red), PICLO offset $44
.alias SPLFU6           $3BA2    ;Vector ROM picture: fuseball-kills-player explosion frame 6 of 7 (red), PICLO offset $46
.alias SPLFU7           $3BA8    ;Vector ROM picture: fuseball-kills-player explosion frame 7 of 7 (blue), PICLO offset $48
.alias SHRAP            $3BAE    ;Vector ROM picture: yellow player-death shrapnel pieces placed via the vector RAM SCALE list, PICLO offset $3A
.alias FUSE0            $3C6A    ;Vector ROM picture: fuseball animation frame 0 of 4, PICLO offset $4E (PTFUSE), chosen at $B6EC
.alias FUSE1            $3CB2    ;Vector ROM picture: fuseball animation frame 1 of 4, PICLO offset $50 (PTFUSE+2)
.alias FUSE2            $3CFC    ;Vector ROM picture: fuseball animation frame 2 of 4, PICLO offset $52 (PTFUSE+4)
.alias FUSE3            $3D44    ;Vector ROM picture: fuseball animation frame 3 of 4, PICLO offset $54 (PTFUSE+6)
.alias FUSEX1           $3D8A    ;Vector ROM picture: fuseball kill score '750', PICLO offset $56 (PTFUSX)
.alias FUSEX2           $3D96    ;Vector ROM picture: fuseball kill score '500', PICLO offset $58 (PTFUSX+2)
.alias FUSEX3           $3DA4    ;Vector ROM picture: fuseball kill score '250', PICLO offset $5A (PTFUSX+4)
.alias JSRDOT           $3DB2    ;Vector ROM: a JSRL JADOT word that WHITIP ($C72D) copies into vector RAM to draw a white dot at a tip
.alias SWNORM           $3DB4    ;Vector ROM: play master display list, JSRL every vector RAM sub-buffer then JMPL VECRAM. First JMPMAL entry
.alias SWMSGS           $3DC8    ;Vector ROM: messages-only master display list (JSRL SWINFO, JMPL VECRAM). Second JMPMAL entry
.alias SWHALT           $3DCC    ;Vector ROM: master display list that just halts the vector generator. Third JMPMAL entry
.alias BOKLIT           $3DCE    ;Vector ROM: bookkeeping screen literals (seconds on, games played, averages), drawn by DBOOKE ($DD7E)
.alias SYSOPT           $3F16    ;Vector ROM: .WORD table of self-test option literal pictures (ENTEST, ZTIMES, ZHISCO, ZMED, ZEASY, ZHARD) for DSPSYS
.alias VORLIT           $3F4E    ;Vector ROM: the TEMPEST logo letters (TEMLIT), drawn as the approaching logo rainbow by LOGPRO ($B131)
.alias KILLER           $3FF2    ;Vector ROM: beam killer, blank vectors to the screen corners. VGJSRL'd by ZATC1S ($B1AF) and DSBOOM ($B8BA)

;----------------------------------[ Constants ]----------------------------------
;ALCOMN.MAC  CONSTANTS-COUNTS
.alias SPACG            $00      ;Assembly switch = 0 that suppresses the space game code (.IF NE,SPACG blocks) in ALCOMN, ALDIS2 and ALVROM
.alias NHISCO           $08      ;# OF HIGH SCORES KEPT
.alias NRANKS           $63      ;Highest rank number (99). Rank display ONERNK caps at it and hi score ranking compares against it
;ALCOMN.MAC  CONSTANTS-STATE CODES
.alias CNEWGA           $00      ;Game state code $00 (QSTATE, ROUTAD index): NEWGAM, start a new game. MAINLN sets it at power up
.alias CNEWLI           $02      ;Game state code $02 (QSTATE, ROUTAD index): NEWLIF, new life setup after losing a base
.alias CPLAY            $04      ;Game state code $04 (QSTATE, ROUTAD index): PLAY, normal game play
.alias CENDLI           $06      ;Game state code $06 (QSTATE, ROUTAD index): ENDLIF, life lost. Set at $A563
.alias CENDGA           $08      ;Game state code $08 (QSTATE, ROUTAD index): ENDGAM, end of game. Set at $90B1
.alias CPAUSE           $0A      ;Game state code $0A (QSTATE, ROUTAD index): PAUSE, wait for the QTMPAUS timer then go to QNXTSTA
.alias CNEWAV           $0C      ;Game state code $0C (QSTATE, ROUTAD index): new wave. Its ROUTAD entry is $0000 and nothing sets it
.alias CENDWAV          $0E      ;Game state code $0E (QSTATE, ROUTAD index): ENDWAV, end of wave (initialise space mode). Set at $9827
.alias CHISCHK          $10      ;Game state code $10 (QSTATE, ROUTAD index): HISCHK, check for high scores. Set at $CA13
.alias CDLADR           $14      ;Game state code $14 (QSTATE, ROUTAD index): DLADR, display the high score table (ladder)
.alias CGETINI          $12      ;Game state code $12 (QSTATE, ROUTAD index): GETINI, get high score initials. Set at $A656
.alias CNOTFOU          $14      ;Same value as CDLADR ($14): state INTLDR loads when no player needs initials or the entry timer runs out
.alias CREQRAT          $16      ;Game state code $16 (QSTATE, ROUTAD index): PRORAT, request player rate (skill level select). Set at $9133
.alias CNEWV2           $18      ;Game state code $18 (QSTATE, ROUTAD index): NEWAV2, new wave part 2 (zoom). Score display tests it for starfield messages
.alias CLOGO            $1A      ;LOGO INIT
.alias CINIRAT          $1C      ;Game state code $1C (QSTATE, ROUTAD index): INIRAT, initialise the rate request (monster delay and display)
.alias CNWLF2           $1E      ;Game state code $1E (QSTATE, ROUTAD index): NEWLF2, new life part 2. ALDIS2 then centres the well Z at once
.alias CDROP            $20      ;DROP MODE
.alias CSYSTM           $22      ;Game state code $22 (QSTATE, ROUTAD index): SYSTEM, self-test system info display. NONSTA sets it when MTEST is on
.alias CBOOM            $24      ;BOOM STATE
.alias CDPLAY           $00      ;PLAY
.alias CDSYST           $02      ;SYSTEM CONFIGURATION
.alias CDREQRA          $08      ;REQUEST RANK
.alias CDPLPL           $0E      ;PLAY PLAYER WARNING
.alias CDGOVR           $0C      ;GAME OVER PLAYER MSG
.alias CDHITB           $0A      ;HI SCORE TABLE
.alias CDGETI           $06      ;GET INITIALS
.alias CDBOOM           $04      ;BOOM DISPLAY
.alias CDPRST           $10      ;"PRESS START"
.alias CD2GAM           $16      ;"2 GAME MIN"
.alias CDBOXP           $12      ;LOGO BOX
.alias CDLOGP           $14      ;LOGO ITSELF
.alias SECOND           $14      ;FRAMES/SECOND
.alias QUASEC           $05      ;QUARTER SECOND FACTOR
;ALCOMN.MAC  BOOM
.alias NPARTI           $10      ;# OF PARTICLES
.alias PARLXA           $20      ;FRACTIONAL
.alias PARLYA           $20      ;Boom particle deceleration, Y fractional part ($20). Defined in ALCOMN BOOM section, unused by rev 3 code
.alias PARLZA           $20      ;Boom particle deceleration, Z fractional part ($20). Defined in ALCOMN BOOM section, unused by rev 3 code
.alias PARTXA           $00      ;INTEGER (POSITIVE)
.alias PARTYA           $00      ;Boom particle deceleration, Y integer part (0). Defined in ALCOMN BOOM section, unused by rev 3 code
.alias PARTZA           $00      ;Boom particle deceleration, Z integer part (0). Defined in ALCOMN BOOM section, unused by rev 3 code
.alias LEDOFF           $03      ;MLED1 or MLED2 ($03), written by the self test at $D8F0 to turn the start LEDs off
.alias NROMS            $0C      ;Number of program ROMs checksummed by the self test (12). Sizes the CHKSMS array and the BADBOX report loop
;ALCOMN.MAC  HARDWARE DEFINITIONS
.alias MCOINR           $01      ;RIGHT COIN MECH
.alias MCOINC           $02      ;CENTER COIN MECH
.alias MCOINL           $04      ;LEFT COIN MECH
.alias S_LMBIT          $08      ;SLAM
.alias MTEST            $10      ;SELF TEST
.alias MDITES           $20      ;DIAGNOSTIC TEST SWITCH
.alias MHALT            $40      ;VG HALT
.alias M3KHTI           $80      ;3 KHZ TIMER
.alias ROMSTART         $3000    ;ROM START (VECTOR ROM)
.alias MRCCNT           $01      ;RIGHT COIN COUNTER
.alias MMCCNT           $02      ;CENTER
.alias MLCCNT           $04      ;LEFT
.alias MVINVX           $08      ;VIDEO INVERT X
.alias MVINVY           $10      ;VIDEO INVERT Y
.alias MLED1            $02      ;LED 1
.alias MLED2            $01      ;LED 2
.alias MFLIP            $04      ;FLIP (=1 FOR PLAYER 2)
.alias MSTRT1           $20      ;START 1
.alias MSTRT2           $40      ;START 2
.alias MSUZA            $08      ;SUPPERZAPPER
.alias MFIRE            $10      ;FIRE
.alias MFAKE            $80      ;FAKE INPUT
.alias MOPT13           $07      ;SPECIAL OPTIONS
.alias COCKTA           $10      ;=1 IF COCKTAIL
.alias MOPTI4           $20      ;SPECIAL OPTION
.alias OM2GAM           $01      ;2 GAME MIN OPTION MASK
.alias BLUE             $06      ;Colour RAM index 6, the blue well colour (WELCOL). Also blue stars in waves 1-4. ALVROM uses BLUE=7 locally
.alias BLULET           $07      ;Colour RAM index 7, blue for letters. Used for blue messages (MCMLXXX ATARI, APPROACH, NEW SUPER)
.alias GREEN            $05      ;Colour RAM index 5, green. Letters (LETCOL) and trailers (TRACOL)
.alias RED              $03      ;Colour RAM index 3, red. Invaders (INVCOL) and flippers (FLICOL)
.alias YELLOW           $01      ;Colour RAM index 1, yellow. Cursor (CURCOL) and player shots (PCHCOL)
.alias WHITE            $00      ;Colour RAM index 0, white. Explosions, enemy shots and super zap. Also the pulse-on spoke colour
.alias PURPLE           $02      ;Colour RAM index 2, purple. Tankers (TANCOL)
.alias TURQOI           $04      ;Colour RAM index 4, turquoise. Pulsars and the pulse-off spoke colour
.alias WELCOL           $06      ;WELL
.alias CURCOL           $01      ;CURSOR
.alias ICHCOL           $00      ;ENEMY SHOTS
.alias PCHCOL           $01      ;PLAYER SHOTS
.alias INVCOL           $03      ;INVADERS
.alias LETCOL           $05      ;LETTERS
.alias DEPCOL           $06      ;Equated to WELCOL (colour RAM index 6) in ALCOMN. Not referenced by the rev 3 code
.alias EXPCOL           $00      ;EXPLOSION
.alias FLICOL           $03      ;FLIPPERS
.alias TANCOL           $02      ;TANKER
.alias TRACOL           $05      ;TRALERS
.alias ZAPCOL           $00      ;SUPER ZAP
.alias FRED             $0C      ;Colour RAM value $0C (active low, b0 and b1 clear): red gun on. ANDed to build the Z colour values
.alias FBLUE            $0B      ;Colour RAM value $0B (active low, b2 clear): blue gun on. ANDed to build the Z colour values
.alias FGREEN           $07      ;Colour RAM value $07 (active low, b3 clear): green gun on. ANDed to build the Z colour values
.alias HRED             $0D      ;Colour RAM value $0D (active low, only b1 red clear, red-low off). Defined in ALCOMN, not referenced
.alias ZWHITE           $00      ;Colour RAM value $00 (all guns on), white. Used in the COLTAB wave colour sets
.alias ZYELLO           $04      ;Colour RAM value $04 (red and green), yellow. COLTAB entry and the plenty-of-shots indicator colour
.alias ZPURPL           $08      ;Colour RAM value $08 (red and blue), purple. Used in the COLTAB wave colour sets
.alias ZRED             $0C      ;Colour RAM value $0C (red), red. COLTAB entry, splat colour (ALTCOL) and the out-of-shots indicator
.alias ZTURQOI          $03      ;Colour RAM value $03 (green and blue), turquoise. Used in the COLTAB wave colour sets
.alias ZGREEN           $07      ;Colour RAM value $07 (green), green. Used in the COLTAB wave colour sets
.alias ZBLUE            $0B      ;Colour RAM value $0B (blue), blue. COLTAB well colour and the low-shots indicator colour
.alias ZBLACK           $0F      ;Colour RAM value $0F (all guns off), black. COLTAB uses it at $C223 for the well colour of one wave set
.alias PSHCTR           $08      ;PLAYER SOT CENTER
.alias PDIWHI           $09      ;PLAYER DEATH EXPLOSION COLORS
.alias PDIYEL           $0A      ;Colour RAM index 10, player death explosion yellow. ALTCOL ($B868) loads ZYELLO into it
.alias PDIRED           $0B      ;Colour RAM index 11, player death explosion red. ALTCOL ($B861) loads ZRED into it
.alias NYMCOL           $0C      ;NYMPHE
.alias FLASH            $0F      ;CHANGES EVERY 4 MO.
;ALCOMN.MAC  VARIABLES-CONTROL
.alias MATRACT          $80      ;D7: 0=ATTRACT 1=GAME
.alias MGTMOD           $40      ;D6:0=NO TIME;START ALLOWED
.alias MECHS            $03      ;Number of coin mechanisms (3) for the COIN65 coin routine. Sizes $CNSTT and $PSTSL
.alias EMCTRS           $03      ;Number of electromechanical coin counters (3) for COIN65. Sizes $CCTIM
;ALCOMN.MAC  VARIABLES-DISPLAY
.alias CBUF1            $78      ;FOLLOWING BUFFER MAY BE USED FOR OTHER PURPOSES
;ALCOMN.MAC  CONSTANTS-COUNTS
.alias NPLANE           $08      ;Number of star field planes (8). Size of PLANEY
.alias NINVAD           $07      ;Number of invader slots (7). Size of INVAC1, INVAC2, INVCAM and the other invader tables
.alias NLINES           $10      ;Number of well lines and spokes (16). Size of the enemy line (spike) tables LINSXH and others
.alias NNYMPH           $40      ;Number of nymph slots (64), the enemies waiting to emerge. Size of NYMPL and NYMPY
.alias NPCHARG          $08      ;Number of player shot slots (8). They come first in the charge tables. Size of CHARCO
.alias NICHARG          $04      ;Number of enemy shot slots (4), after the player shots in the charge tables
.alias NCHARG           $0C      ;Total charge (shot) slots, NPCHARG+NICHARG = 12. Size of CHARL1, CHARL2, CHARY, CHARYL
.alias NEXPLO           $08      ;Number of explosion slots (8). Size of EXPLX, EXPLY, EXPLZ, EXPLPI
;ALCOMN.MAC  CONSTANTS-PLAYFIELD
.alias ILINDDY          $F0      ;Y position $F0 at the far (bottom) end of the well. Objects start there and it is the end of a descent
.alias ILINLIY          $10      ;Y position $10 at the near rim (top) of the well where the player's cursor sits
;ALCOMN.MAC  VARIABLES-OBJECT LOCATION + STATUS
.alias INVABI           $07      ;INVAC1 mask $07: invader appearance code (0 flipper, 1 pulsar, 2 tanker, 3 trailer, 4 fuse)
.alias ZABFLI           $00      ;APPEARANCE:0=FLIPPER
.alias ZABPUL           $01      ;1=PULSAR
.alias ZABTAN           $02      ;2=TANKER
.alias ZABTRA           $03      ;3=TRALER
.alias ZABFUS           $04      ;4=FUSE
.alias INVSEQ           $18      ;INVAC1 mask $18: invader animation sequence bits (read at $B5C2)
.alias INVMOT           $80      ;INVAC1 mask $80: motion flag, 1 while the invader is flipping or leaping (ZMOTJM)
.alias ZMOTMO           $00      ;MOTION:0=NOT FLIPPING/LEAPING
.alias ZMOTJM           $80      ;1=FLIPPER/LEAPING
.alias INVROT           $40      ;INVAC1 mask $40: rotation direction of a flip, 0 clockwise and 1 counter-clockwise
.alias ZROTCW           $00      ;ROTATIONAL DIRECTION:0=CW
.alias ZROCCW           $40      ;INVAC1 rotation value $40 (INVROT set): flipping counter-clockwise
.alias INVCAR           $03      ;INVAC2 mask $03: what a tanker carries (0 nothing, 1 flippers, 2 pulsars, 3 fuses)
.alias ZCARNO           $00      ;CARRIER (0=NOTHING)
.alias ZCARFL           $01      ;1=FLIPPERS
.alias ZCARPU           $02      ;2=PULSARS
.alias ZCARFU           $03      ;3=FUSES
.alias INVFIR           $40      ;FIREPOWER (0=NO FIRE, 1=FIRE)
.alias ZFIRNO           $00      ;INVAC2 firepower value 0: invader does not fire. Used in the TNEWI2 new-invader table
.alias ZFIRYE           $40      ;INVAC2 firepower value $40 (INVFIR): invader may fire. Used in skill tables and TNEWI2
.alias INVDIR           $80      ;DIRECTION (0=UP, 1=DOWN)
.alias ZDIRUP           $00      ;INVAC2 direction value 0: invader moving up the well. Used in TNEWI2
.alias ZDIRDO           $80      ;INVAC2 direction value $80 (INVDIR): invader moving down. ORed in at $9FF0 to send it down
.alias PCVELO           $09      ;PLAYER SHOT VELOCITY (I)
.alias PULVEL           $FEA0    ;PULSAR VELOCITY (IF)
;ALDIS2.MAC  GLOBALS
.alias RATS             $C0      ;Beam intensity $C0 loaded into VGBRIT for well spokes, rim lines and depth-cued line pictures
.alias MZCOLO           $08      ;NEW COLOR STAT BIT MASK
.alias MZBRIT           $00      ;NEW INTENSITY STAT BIT
;ALDIS2.MAC  TABLE-WORLD COORD OFFSETS (X,Z) FOR JUMPERS
.alias DG000            $2C      ;Jumper world offset $2C for 0 degrees, first byte of JUMPX in the flipper jump coordinate tables ($B68B)
;ALDIS2.MAC  SPECIAL EXPLOSION DATABASE
.alias CPSPXI           $FFFF    ;Special explosion start index -1 (SPXIND) for a charge hitting the player: splat sequence from TSPTIM index 0
.alias PPSPXI           $07      ;Special explosion start index 7 (PPSTART-TSPTIM-1) for a pulsar killing the player. Loaded at $A347
.alias FPSPXI           $09      ;Special explosion start index 9 (FPSTART-TSPTIM-1) for a fuse killing the player (SPLFU pictures). Loaded at $A343
;ALDIS2.MAC  TABLES-WELL COORDINATES(WORLD)
.alias DG0              $F0      ;Circle well coordinate $F0 (angle 0, $70+$80), in the NEWLIX ($B97C) and NEWLIZ ($BA7C) well shape tables
.alias DI0              $F0      ;Square well coordinate $F0 (outer edge), in the NEWLIX ($B98C) and NEWLIZ ($BA8C) tables
.alias DI1              $B8      ;Square well coordinate $B8, in the NEWLIX and NEWLIZ well shape tables
.alias DI2              $80      ;Square well coordinate $80 (centre), in the NEWLIX and NEWLIZ well shape tables
.alias DI3              $48      ;Square well coordinate $48, in the NEWLIX and NEWLIZ well shape tables
.alias DI4              $10      ;Square well coordinate $10 (opposite edge), in the NEWLIX and NEWLIZ well shape tables
.alias CR0              $F0      ;Cross well coordinate $F0 ($70+$80), in the NEWLIX ($B99C) and NEWLIZ ($BA9C) well shape tables
.alias CR1              $F0      ;Cross well coordinate $F0 ($70+$80), in the NEWLIX and NEWLIZ well shape tables
.alias CR2              $B8      ;Cross well coordinate $B8 ($38+$80), in the NEWLIX and NEWLIZ well shape tables
.alias CR3              $B8      ;Cross well coordinate $B8 ($38+$80), in the NEWLIX and NEWLIZ well shape tables
.alias CR4              $80      ;Cross well coordinate $80 (centre), in the NEWLIX and NEWLIZ well shape tables
.alias PX0              $EC      ;Peanut well X coordinate $EC ($6C+$80), in NEWLIX at $B9AC
.alias PX1              $D5      ;Peanut well X coordinate $D5 ($55+$80), in NEWLIX at $B9AC
.alias PX2              $B1      ;Peanut well X coordinate $B1 ($31+$80), in NEWLIX at $B9AC
.alias PX3              $90      ;Peanut well X coordinate $90 ($10+$80), in NEWLIX at $B9AC
.alias PZ0              $94      ;Peanut well Z coordinate $94 ($14+$80), in NEWLIZ at $BAAC
.alias PZ1              $B0      ;Peanut well Z coordinate $B0 ($30+$80), in NEWLIZ at $BAAC
.alias PZ2              $B8      ;Peanut well Z coordinate $B8 ($38+$80), in NEWLIZ at $BAAC
.alias PZ3              $A7      ;Peanut well Z coordinate $A7 ($27+$80), in NEWLIZ at $BAAC
;ALDIS2.MAC  PICTURES
.alias CINVA1           $00      ;Line picture number 0 (PCOUNT and PINDEX index): the flipper (INVADER 1). Used by FLITAB and at $B605
.alias CNCURS           $01      ;Line picture number 1: base of the 8 player cursor pictures NCRS1-NCRS8. ADCed with the cursor position at $B5A7
.alias CPULS4           $09      ;Line picture number 9: pulsar picture PULS4. Last entries of PULTAB
.alias CPULS3           $0A      ;Line picture number 10: pulsar picture PULS3, in PULTAB
.alias CPULS2           $0B      ;Line picture number 11: pulsar picture PULS2, in PULTAB
.alias CPULS1           $0C      ;Line picture number 12: pulsar picture PULS1, in PULTAB
.alias CPULS0           $0D      ;Line picture number 13: pulsar picture PULS0, first entry of PULTAB
;ALEARO.MAC  HARDWARE DEFINITIONS
.alias EACK             $01      ;CLOCK BIT
.alias EAC1             $04      ;C1 (INVERTED TO CHIP)
.alias EAC2             $02      ;C2
.alias EACE             $08      ;CHIP SELECT
.alias EAERAS           $80      ;EAROM request bit D7 = erase then write. Default request in the EAROM handler at $DE3A and $DE8E
.alias EAWRIT           $40      ;EAROM request bit D6 = write. Loaded at $DE82
.alias EAREAD           $20      ;EAROM request bit D5 = read. Loaded at $DE44
;ALHAR2.MAC  GLOBALS
.alias QCHKS2           $4D      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM2 at $9008 in ALWELG
.alias QCHKS3           $16      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM3 at $9D05 in ALWELG
.alias QCHKS4           $AB      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM4 at $A462 in ALWELG
.alias QCHKS5           $E1      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM5 at $A8AF in ALWELG
.alias QCHKS6           $1D      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM6 at $B497 in ALDIS2
.alias QCHKS7           $3E      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM7 at $BCFC in ALDIS2
.alias QCHKS8           $DB      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM8 at $C472 in ALDIS2
.alias QCHKS9           $00      ;ROM checksum balance byte (ALHAR2), assembled as CHKSM9 at $CCAF in ALSOUN
.alias QCHKSA           $7C      ;ROM checksum balance byte (ALHAR2), assembled as CHKSMA at $D703 in ALHAR2
.alias QCHKSB           $73      ;ROM checksum balance byte (ALHAR2), assembled as CHKSMB at $DDDC in ALTES2
;ALLANG.MAC  MESSAGES: COLOR, SCALE, Y POSITION, LANGUAGE PTRS
.alias MGAMOV           $00      ;GAME OVER
.alias MPLAYR           $02      ;PLAYER (BIG)
.alias MPLYR2           $04      ;PLAYER (NORMAL)
.alias MPRESS           $06      ;PRESS START
.alias MPLAY            $08      ;PLAY
.alias MENTER           $0A      ;ENTER
.alias MPRMOV           $0C      ;SPIN
.alias MPRFIR           $0E      ;PRESS FIRE
.alias MHIGHS           $10      ;HIGH SCORE
.alias MRANK            $12      ;RANK
.alias MRATE            $14      ;RATE YOURSELF
.alias MNOVIC           $16      ;NOVICE
.alias MEXPER           $18      ;EXPERT
.alias MBONUS           $1A      ;BONUS
.alias MTIME            $1C      ;TIME
.alias MLEVEL           $1E      ;LEVEL
.alias MHOLE            $20      ;HOLE
.alias MINSER           $22      ;INSERT COINS
.alias MCMODE           $24      ;FREE PLAY
.alias MCMOD1           $26      ;1 COIN 2 PLAYS
.alias MCMOD2           $28      ;1 COIN 1 PLAY
.alias MCMOD3           $2A      ;2 COINS 1 PLAY
.alias MATARI           $2C      ;MCMLXXX ATARI
.alias MCREDI           $2E      ;CREDITS
.alias MBONPT           $30      ;BONUS PTS
.alias M2GAME           $32      ;2 GAME MINIMUM
.alias MBOLIF           $34      ;BONUS EVERY
.alias MSPIKE           $36      ;AVOID SPIKES
.alias MAPROA           $38      ;APPROACH
.alias MSUPZA           $3A      ;NEW SUPER
;ALLANG.MAC  LITERALS
.alias ZATLIC           $10      ;Length of the MCMLXXX ATARI literal (ZATLIE-ZATLIS). Loop count for the ZATLIV tamper check into QT1
;ALSCO2.MAC  *****************************************
.alias ITIMHI           $60      ;Start value ($60) of TIMHIS, the high score initials entry timer (counted down every 32 frames)
.alias CBLANK           $1A      ;Character code 26, a blank initial. Fills the initials when a new high score entry is prepared
;ALSCO2.MAC  INFOR DISPLAY-CREDITS,COPYRIGHT
.alias ZATC4C           $0A      ;Length of the ZATC4S-ZATC4E code (copyright and credits MSGS calls). Loop count for the ZATC4V check into QT2
;ALSCO2.MAC  LOGO INITIALIZATION
.alias FARINC           $08      ;Step (8) added to NEARY each frame in BOXPRO, the logo shrinking box rainbow
;ALSOUN.MAC  GLOBLS
.alias NCHANL           $10      ;Number of sound half-channels (16, frequency and control for 8 POKEY channels). Sizes POINT, CURRENT, FRAMES, COUNT
;ALSOUN.MAC  SOUND DESCRIPTION
.alias STVAL            $00      ;VALUE TO START SEQUENCE
.alias FRCNT            $01      ;# OF FRAMES BEFORE ANY CHANGE
.alias CHANGE           $02      ;AMOUNT OF CHANGE
.alias NUMBER           $03      ;TOTAL NUMBER OF CHANGES IN THIS SEQUENCE
;ALSOUN.MAC  SOUND TABLES
.alias SIDLO            $0F      ;CURSOR MOVES
.alias SIDEX            $1F      ;ENEMY EXPLOSION
.alias SIDLA            $2F      ;PLAYER FIRE
.alias SIDPU            $3F      ;PULSATION
.alias SIDWP            $4F      ;SPECIAL SCORE
.alias SIDDI            $5F      ;PLAYER DIES
.alias SIDT2            $6F      ;THRUST IN TUBE
.alias SIDT3            $7F      ;THRUST IN SPACE
.alias SIDES            $8F      ;ENEMY SHOT
.alias SIDEL            $9F      ;ENEMY LINE DESTRUCTION
.alias SIDSL            $AF      ;SLAM
.alias SIDS3            $BF      ;3 SECONDS LEFT WARNING
.alias SIDPO            $CF      ;PULSAR OFF
.alias AUDCV            $00      ;Value (0) written to POKEY 1 AUDCTL by the sound initialisation at $CDD3
.alias AUDCV2           $00      ;Value (0) written to POKEY 2 AUDCTL (AUD2CT) by the sound initialisation at $CDD8
;ALTES2.MAC  DATABASE
.alias MBCOND           $78      ;Self-test result byte $78 (CBUF1): bad Mathbox flag, set at $DC17
.alias RAMCND           $79      ;Self-test result byte $79: bad RAM report, set by BRAMREP at $D8CD
.alias PK1CND           $7A      ;Self-test result byte $7A: bad POKEY 1 flag, set at $DA51
.alias PK2CND           $7B      ;Self-test result byte $7B: bad POKEY 2 flag, set at $DA60
.alias EARCND           $7C      ;Self-test result byte $7C: bad EAROM flag, set at $DA6C and $DB68
.alias CHKSMS           $7D      ;Self-test array at $7D of NROMS ROM checksums, stored at $DA27 and reported by BADBOX
;ALVROM.MAC  SUB-BUFFER DEFINITIONS
.alias BCINFO           $00      ;Vector RAM sub-buffer code 0: information (scores, messages). Index into BUFASL, BUFBSL, BUFSWL and JMPALO
.alias BCENEL           $01      ;Vector RAM sub-buffer code 1: enemy lines (spikes). Index into the sub-buffer pointer tables
.alias BCWELL           $02      ;Vector RAM sub-buffer code 2: the well. Index into the sub-buffer pointer tables
.alias BCINVA           $03      ;Vector RAM sub-buffer code 3: invaders. Index into the sub-buffer pointer tables
.alias BCSHOT           $04      ;Vector RAM sub-buffer code 4: shots (charges). Index into the sub-buffer pointer tables
.alias BCNYMP           $05      ;Vector RAM sub-buffer code 5: nymphs. Index into the sub-buffer pointer tables
.alias BCEXPL           $06      ;Vector RAM sub-buffer code 6: explosions. Index into the sub-buffer pointer tables
.alias BCCURS           $07      ;Vector RAM sub-buffer code 7: player cursor. Index into the sub-buffer pointer tables
.alias BCSTAR           $08      ;Vector RAM sub-buffer code 8: star field. Index into the sub-buffer pointer tables
;ALVROM.MAC  TABLE - POINTER TO PICTURES
.alias PTEXP1           $00      ;EXPLOSION 1 SMALLEST
.alias PTCURS           $08      ;DIAMON DOTS RADIUS 2
.alias PTSTR1           $0A      ;STAR FIELD 1
.alias PTSPI1           $12      ;SPIRALS
.alias PTTANK           $1A      ;TANKER
.alias PTSPAR           $1C      ;SPARKLE
.alias PTESHO           $20      ;ENEMY SHOT
.alias PTSPLA           $28      ;SMALL SPLAT
.alias PTTANP           $4A      ;PULSAR TANKER
.alias PTTANF           $4C      ;FUSE TANKER
.alias PTFUSE           $4E      ;FUSE
.alias PTFUSX           $56      ;FUSE EXPLOSION
;ALWELG.MAC  INITIALIZE-SET SKILL LEVEL FOR WAVE
.alias T1               $02      ;1 BYTE IN PARAMETER FIELD GOES FOR ALL WAVES IN RANGE
.alias TZ               $04      ;1 BYTE IN PARAMETER FIELD FOR EACH WAVE IN RANGE
.alias TE               $00      ;EOT (RETURN WITH 0)
.alias TZANDF           $06      ;AND CURRENT WAVE WITH F, THE DO TZ
.alias TA               $08      ;AND BYTE 4 TO BYTE 3 FOR EACH LEVEL
.alias TB               $0A      ;ADD BYTE 3 TO WINVIN
.alias TR               $0C      ;ALTERNATE BETWEEN BYTES 3 & 4
;ALWELG.MAC  EASY - MED - HARD OPTIONS
.alias ZEASY            $01      ;Difficulty option code 1 (OPTIN3 bits 0-1) = easy: fewer enemy shots, slower. Tested at $932D
.alias ZHARD            $02      ;Difficulty option code 2 (OPTIN3 bits 0-1) = hard: more enemy shots (up to 3), faster. Tested at $934D
;ALWELG.MAC  SKILL CONTOUR TABLES
.alias PN               $28      ;Value 40 in the TPUCHDE pulsar chase delay skill table (waves 17-32, alternating with PC)
.alias PC               $14      ;Value 20 in the TPUCHDE pulsar chase delay skill table (waves 17-32, alternating with PN)
;ALWELG.MAC  PLAY-EXPLOSION OF FUSE INIT
.alias IPTYPE           $05      ;EXPLOSION TYPE CODES
.alias CPTYPE           $01      ;Explosion type code 1: the player's cursor destroyed. Loaded at $A350 before DEADCU
.alias CCTYPE           $00      ;Explosion type code 0: a player shot hits an enemy shot (INCCSQ at $A37C)
.alias CITYPE           $00      ;Explosion type code 0: a player shot kills an invader (INCISQ at $A3B1)
.alias CFTYPE           $02      ;Explosion type code base 2 for a fuse kill. A random 0-2 (250, 500, 750 points) is added at $A327
;ALWELG.MAC  INITIALIZE SUPER ZAP
.alias CSUMAX           $02      ;Superzapper uses allowed per wave (2). PROSUZ compares SUZCNT against it
.alias CSUINT           $01      ;Superzapper kill interval mask (1): KILENE kills one enemy on every other SUZTIM frame
.alias CSUSTA           $03      ;SUZTIM value (3) at which the superzapper starts killing. TIMAX gives 19 frames for zap 1 and 5 for zap 2
