"""Gate V reference data for c_src/avg.c, from the disassembly's Python AVG model.

  python tools/avg_ref.py shapes [OUT]
      Renders every vector-ROM picture exactly as ../disasm/emit_shapes.py does
      (section 1: every labelled picture in $3000-$3FFF via vrender.render;
      section 3: the 41 VGMSGA characters at scale 1.0) and writes the segments
      to OUT (default tests/ref/avg_shapes_ref.txt).  Also checks that the
      segments equal the arrays embedded in ../disasm/shapes_preview.html
      (3-decimal rounding there), so the reference is the published preview.

  python tools/avg_ref.py frame OUTDIR NNNN [NNNN ...]
      Walks tests/ref/frame_NNNN.vram with an AVG walker written here on top of
      avg.decode_raw / avg.scal_factor (vrender.render extended to follow
      vector RAM, hardware 4-slot stack), writes OUTDIR/frame_NNNN.py.txt in
      the same format as tests/avgframe.exe, prints a summary and compares
      ops / vectors / z!=0 with tests/ref/ref_index.json (refrun's walker).

Segment line: x0 y0 x1 y1 colour intensity, coordinates in Q15 (value*32768,
asserted integral), colour -1 = no colour STAT seen.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CSRC = os.path.dirname(HERE)
DISASM = os.path.join(os.path.dirname(CSRC), "disasm")
sys.path.insert(0, DISASM)
import avg, vrender  # noqa: E402


def q15(v):
    q = v * 32768.0
    assert q == int(q), v
    return int(q)


def seg_line(s):
    x0, y0, x1, y1, col, br = s
    return "%d %d %d %d %d %d" % (q15(x0), q15(y0), q15(x1), q15(y1),
                                  -1 if col is None else col, br)


# --------------------------------------------------------------------- shapes
def shapes(out):
    M = vrender.Model()
    mem = M.mem
    import vtables
    tables = vtables.build(M)
    # the C side reads the ROM from vecrom.c: make sure it is the same image
    vec_c = open(os.path.join(CSRC, "vecrom.c")).read()
    body = vec_c[vec_c.index("{") + 1:vec_c.rindex("}")]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    vb = bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body))
    assert vb == bytes(mem[0x3000:0x4000]), "vecrom.c differs from the 64K image"

    recs = []                                  # (key, addr, mode, st0, name, segs)
    for a in sorted(M.label_at):               # emit_shapes.py section 1
        if not (0x3000 <= a <= 0x3FFF):
            continue
        nm = M.label_at[a][0]
        if nm in vrender.DATA_LABELS or nm == "VGMSGA":
            continue
        one = nm in vrender.WORD_LABELS
        st0 = {"x": 0.0, "y": 0.0, "scale": avg.scal_factor(1, 0), "color": None, "intensity": 12}
        segs, _c, _i = vrender.render(mem, a, one_op=one, state=dict(st0))
        recs.append(("V%04X" % a, a, "oneop" if one else "full", st0, nm, segs))
    for c in tables["characters"]["entries"]:  # emit_shapes.py section 3
        t = int(c["target"][1:], 16)
        st0 = {"x": 0.0, "y": 0.0, "scale": 1.0, "color": None, "intensity": 12}
        segs, _c, _i = vrender.render(mem, t, state=dict(st0))
        recs.append(("G%d" % c["index"], t, "full", st0, "char %d" % c["index"], segs))

    # cross-check with the published preview page
    page = open(os.path.join(DISASM, "shapes_preview.html"), encoding="utf-8").read()
    pub = {k: json.loads(v) for k, v in re.findall(r"S\['(V[0-9A-F]{4})'\]=(\[.*?\]);\n", page)}
    gm = re.search(r"var G=(\[.*?\]);\nvar M", page, re.S)
    gl = re.findall(r"\{s:(\[.*?\]),a:", gm.group(1))
    for i, s in enumerate(gl):
        pub["G%d" % i] = json.loads(s)
    mism = 0
    for key, _a, _m, _st, _nm, segs in recs:
        ref = pub.get(key)
        want = [[float(vrender_fmt(v)) for v in s[:4]] + [-1 if s[4] is None else s[4], s[5]] for s in segs]
        if ref is None or len(ref) != len(want) or any(
                [float(x) for x in r[:4]] + list(r[4:]) != w for r, w in zip(ref, want)):
            mism += 1
            print("preview page differs for", key)
    print("shapes_preview.html cross-check: %d shapes, %d differ, %d page entries" % (len(recs), mism, len(pub)))

    with open(out, "w", newline="\n") as f:
        f.write("# GENERATED by c_src/tools/avg_ref.py shapes - Gate V reference (disasm/vrender.py)\n")
        f.write("# SHAPE key addr mode scale_q15 colour intensity nseg name / segments / END\n")
        for key, a, mode, st0, nm, segs in recs:
            f.write("SHAPE %s %04X %s %d %d %d %d %s\n" % (
                key, a, mode, q15(st0["scale"]), -1 if st0["color"] is None else st0["color"],
                st0["intensity"], len(segs), vrender.clean(nm)))
            for s in segs:
                f.write(seg_line(s) + "\n")
            f.write("END\n")
    print("wrote %s: %d shapes, %d segments" % (out, len(recs), sum(len(r[5]) for r in recs)))
    return 0 if mism == 0 else 1


def vrender_fmt(v):
    return "%g" % round(float(v), 3)


# --------------------------------------------------------------------- frames
def walk_frame(mem, start=0x2000, budget=20000):
    st = {"x": 0.0, "y": 0.0, "scale": 0.0, "color": 0, "intensity": 0}
    stack, sp, depth = [0, 0, 0, 0], 0, 0
    segs, pc, ops, maxd, over = [], start, 0, 0, False
    stop = "BUDGET"
    while True:
        if ops >= budget:
            break
        if not (0x2000 <= pc <= 0x3FFE):
            stop = "BADADDR"
            break
        d = avg.decode_raw(mem, pc)
        if d["op"] == "VCTR" and pc + 3 > 0x3FFF:
            stop = "BADADDR"
            break
        ops += 1
        op = d["op"]
        if op in ("VCTR", "SVEC"):
            nx = st["x"] + d["dx"] * st["scale"]
            ny = st["y"] + d["dy"] * st["scale"]
            br = st["intensity"] if d["z"] == 1 else d["z"] * 2
            segs.append((st["x"], st["y"], nx, ny, st["color"], br, d["z"]))
            st["x"], st["y"] = nx, ny
        elif op == "SCAL":
            st["scale"] = avg.scal_factor(d["b"], d["l"])
        elif op in ("CSTAT", "STAT"):
            if d["color"] is not None:
                st["color"] = d["color"]
            else:
                st["intensity"] = d["intensity"]
        elif op == "CNTR":
            st["x"] = st["y"] = 0.0
        elif op == "JSRL":
            stack[sp & 3] = pc + 2
            sp = (sp + 1) & 15
            depth += 1
            maxd = max(maxd, depth)
            over |= depth > 4
            pc = d["target"]
            continue
        elif op == "RTSL":
            if depth == 0:
                stop = "RTSL"
                break
            depth -= 1
            sp = (sp - 1) & 15
            pc = stack[sp & 3]
            continue
        elif op == "JMPL":
            if d["target"] == start and depth == 0:
                stop = "LOOP"
                break
            pc = d["target"]
            continue
        elif op == "HALT":
            stop = "HALT"
            break
        pc += d["len"]
    return segs, ops, stop, maxd, over


def summary(segs, ops, stop, maxd, over):
    lit = [s for s in segs if s[5] > 0]
    nz = sum(1 for s in segs if s[6] != 0)
    if lit:
        xs = [q15(v) for s in lit for v in (s[0], s[2])]
        ys = [q15(v) for s in lit for v in (s[1], s[3])]
        bb = "%d %d %d %d" % (min(xs), min(ys), max(xs), max(ys))
    else:
        bb = "none"
    return "STOP %s ops=%d seg=%d lit=%d z=%d depth=%d over=%d bbox=%s" % (
        stop, ops, len(segs), len(lit), nz, maxd, 1 if over else 0, bb)


def frames(outdir, nums):
    img = bytearray(avg.load_image())
    idx = {f["frame"]: f for f in json.load(open(os.path.join(CSRC, "tests", "ref", "ref_index.json")))["frames"]}
    os.makedirs(outdir, exist_ok=True)
    bad = 0
    for n in nums:
        n = int(n)
        vram = open(os.path.join(CSRC, "tests", "ref", "frame_%04d.vram" % n), "rb").read()
        mem = bytearray(img)
        mem[0x2000:0x3000] = vram
        segs, ops, stop, maxd, over = walk_frame(bytes(mem))
        summ = summary(segs, ops, stop, maxd, over)
        with open(os.path.join(outdir, "frame_%04d.py.txt" % n), "w", newline="\n") as f:
            for s in segs:
                f.write(seg_line(s[:6]) + "\n")
            f.write(summ + "\n")
        r = idx.get(n)
        chk = ""
        if r:
            ok = r["avg_ops"] == ops and r["vectors"] == len(segs) and \
                r["bright"] == sum(1 for s in segs if s[6] != 0) and r["list_end"] == stop
            chk = "ref_index ops=%d vectors=%d bright=%d end=%s -> %s" % (
                r["avg_ops"], r["vectors"], r["bright"], r["list_end"], "same" if ok else "DIFFERENT")
            bad += not ok
        print("frame %04d: %s | %s" % (n, summ, chk))
    return 1 if bad else 0


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "shapes":
        sys.exit(shapes(sys.argv[2] if len(sys.argv) > 2 else os.path.join(CSRC, "tests", "ref", "avg_shapes_ref.txt")))
    if len(sys.argv) >= 4 and sys.argv[1] == "frame":
        sys.exit(frames(sys.argv[2], sys.argv[3:]))
    print(__doc__)
    sys.exit(2)
