#!/usr/bin/env python3
"""Generate state_defs.h (RAM symbol aliases) from ../disasm/tempest_defines.asm.

Same rule as the Space Duel port's tools/gen_state.py (the defines files share
the ";---[ Section ]---" layout):

  * every .alias outside "Constants" becomes an address constant
        #define A_NAME  0xADDR
  * aliases in the three VARIABLE sections ("Zero page variables", "Stack page",
    "Game RAM") inside CPU RAM $0000-$07FF also become the cell as an lvalue
        #define NAME    (g.ram[A_NAME])
  * "Constants" aliases are values, not addresses:
        #define K_NAME  0xVALUE

Region markers (Memory map), hardware registers, Vector RAM and Vector ROM get
the address constant only: translated code reaches hardware through the hw_*
seam and vector RAM through VRAM(A_NAME + i).

Rerun after regenerating the disassembly:   python c_src/tools/gen_state.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CSRC = os.path.normpath(os.path.join(HERE, ".."))
ROOT = os.path.normpath(os.path.join(CSRC, ".."))
SRC = os.path.join(ROOT, "disasm", "tempest_defines.asm")
OUT = os.path.join(CSRC, "state_defs.h")

RAM_END = 0x0800                       # $0000-$07FF is CPU RAM (2 KB)
VAR_SECTIONS = ("Zero page variables", "Stack page", "Game RAM")
CONST_SECTION = "Constants"

SECTION_RE = re.compile(r"^;-*\[\s*(.*?)\s*\]-*$")
ALIAS_RE = re.compile(r"^\.alias\s+(\w+)\s+\$([0-9A-Fa-f]+)\s*(?:;(.*))?$")


def parse(path):
    """[(section, name, value, comment)] in file order."""
    out, section = [], ""
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            m = SECTION_RE.match(line)
            if m:
                section = m.group(1)
                continue
            m = ALIAS_RE.match(line)
            if m:
                out.append((section, m.group(1), int(m.group(2), 16),
                            (m.group(3) or "").strip()))
    return out


def ccomment(text):
    return text.replace("*/", "* /")


def main():
    if not os.path.exists(SRC):
        sys.exit("gen_state: missing %s" % SRC)
    aliases = parse(SRC)
    seen = set()
    nram = nconst = naddr = 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        w = f.write
        w("/* state_defs.h - GENERATED by c_src/tools/gen_state.py from\n"
          " * ../disasm/tempest_defines.asm - do not edit by hand.\n"
          " *\n"
          " * A_NAME = CPU address of an alias.  NAME = the RAM cell as an lvalue\n"
          " * (variable sections only).  K_NAME = a Constants-section value.\n"
          " * Vector RAM: VRAM(A_NAME + i).  Hardware: hw_* (hw.h). */\n\n")
        w("#ifndef STATE_DEFS_H\n#define STATE_DEFS_H\n")
        cur = None
        for sec, name, val, cmt in aliases:
            if sec != cur:
                w("\n/* ---- %s ---- */\n" % sec)
                cur = sec
            if name in seen:
                w("/* duplicate alias %s = $%X skipped */\n" % (name, val))
                continue
            seen.add(name)
            c = ("  /* %s */" % ccomment(cmt)) if cmt else ""
            if sec == CONST_SECTION:
                w("#define K_%-12s 0x%02X%s\n" % (name, val, c))
                nconst += 1
                continue
            w("#define A_%-12s 0x%04X%s\n" % (name, val, c))
            naddr += 1
            if sec in VAR_SECTIONS and val < RAM_END:
                w("#define %-14s (g.ram[A_%s])\n" % (name, name))
                nram += 1
        w("\n#endif /* STATE_DEFS_H */\n")
    print("wrote %s (%d addresses, %d RAM cells, %d constants)"
          % (os.path.normpath(OUT), naddr, nram, nconst))


if __name__ == "__main__":
    main()
