#!/usr/bin/env python3
"""Generate the ROM images the Tempest port and its reference harness link.

Inputs (both written by disasm/gen_from_roms.py from roms/tempest3.zip or
tempest.zip - never hand-transcribed):
  ../disasm/_survey/roms_extracted/tempest3_cpu64k.bin   64K CPU image
  ../disasm/_survey/roms_extracted/tempest3/136002-126.a1  Mathbox mapping PROM
  ../disasm/_survey/roms_extracted/tempest3/136002-127.e1 .. -132.l1  microcode

Outputs (c_src/):
  progrom.c/.h  program ROM $9000-$DFFF  (progrom[addr - 0x9000])
  vecrom.c/.h   vector ROM  $3000-$3FFF  (vecrom[addr - 0x3000])
  mbprom.c/.h   Mathbox: mapping PROM (32 x 8) and the 256 x 24-bit microcode

Microcode nibble order.  MBUCOD.V05's $OUT macro emits each word as three bytes
(A,B | SRC,STALL,FUNC | LDAB,DEST,SIGN,JMP,MULT,CARIN), so bit 23..0 =
A(4) B(4) I2HI I2LO I1 I0 STALL I5..I3 LDAB I8..I6 SIGN JMP MULT CARIN.
The six 4-bit PROMs hold those nibbles low-first: 127.e1 = bits 3-0,
128.f1 = 7-4, 129.h1 = 11-8, 130.j1 = 15-12, 131.k1 = 19-16, 132.l1 = 23-20.
Checked against the source: RSTO's "LDL 0 LDAB 16 JMP" (write AL, uPC $20)
is $1073B4 and RDISP's "OR Z,n NOP STALL" (uPC $10+n) is $0n3B10; this script
asserts both.

Rerun:  python c_src/tools/gen_roms.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CSRC = os.path.normpath(os.path.join(HERE, ".."))
ROOT = os.path.normpath(os.path.join(CSRC, ".."))
EXT = os.path.join(ROOT, "disasm", "_survey", "roms_extracted")
IMAGE = os.path.join(EXT, "tempest3_cpu64k.bin")
PROMDIR = os.path.join(EXT, "tempest3")
MB_MAP = "136002-126.a1"
MB_UCODE = ["136002-127.e1", "136002-128.f1", "136002-129.h1",
            "136002-130.j1", "136002-131.k1", "136002-132.l1"]


def need(path):
    if not os.path.exists(path):
        sys.exit("gen_roms: missing %s (run disasm/gen_from_roms.py first)" % path)
    with open(path, "rb") as f:
        return f.read()


def emit_bytes(name, base, data, what):
    h = os.path.join(CSRC, name + ".h")
    c = os.path.join(CSRC, name + ".c")
    guard = name.upper() + "_H"
    with open(h, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* %s.h - GENERATED by c_src/tools/gen_roms.py - do not edit. */\n" % name)
        f.write("#ifndef %s\n#define %s\n#include <stdint.h>\n" % (guard, guard))
        f.write("#define %s_BASE 0x%04X\n#define %s_SIZE 0x%04X\n"
                % (name.upper(), base, name.upper(), len(data)))
        f.write("extern const uint8_t %s[0x%04X]; /* %s */\n#endif\n" % (name, len(data), what))
    with open(c, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* %s.c - GENERATED by c_src/tools/gen_roms.py from\n"
                " * ../disasm/_survey/roms_extracted/tempest3_cpu64k.bin - do not edit.\n"
                " * %s, CPU $%04X-$%04X. */\n" % (name, what, base, base + len(data) - 1))
        f.write('#include "%s.h"\n\nconst uint8_t %s[0x%04X] = {\n' % (name, name, len(data)))
        for i in range(0, len(data), 16):
            row = ",".join("0x%02X" % b for b in data[i:i + 16])
            f.write("    %s, /* $%04X */\n" % (row, base + i))
        f.write("};\n")
    print("wrote %s.c/.h ($%04X, %d bytes)" % (name, base, len(data)))


def main():
    img = need(IMAGE)
    if len(img) != 0x10000:
        sys.exit("gen_roms: %s is not a 64K image" % IMAGE)
    vec = lambda a: img[a] | (img[a + 1] << 8)
    if (vec(0xDFFC), vec(0xDFFA), vec(0xDFFE)) != (0xD93F, 0xD704, 0xD704):
        sys.exit("gen_roms: vectors at $DFFA are not rev 3's (NMI/RESET/IRQ)")
    emit_bytes("progrom", 0x9000, img[0x9000:0xE000], "program ROM (rev 3)")
    emit_bytes("vecrom", 0x3000, img[0x3000:0x4000], "vector ROM")

    mp = need(os.path.join(PROMDIR, MB_MAP))
    nib = [need(os.path.join(PROMDIR, n)) for n in MB_UCODE]
    if len(mp) != 32 or any(len(x) != 256 for x in nib):
        sys.exit("gen_roms: Mathbox PROM sizes wrong")
    ucode = [sum((nib[k][i] & 0xF) << (4 * k) for k in range(6)) for i in range(256)]
    assert ucode[0x20] == 0x1073B4, "microcode nibble order check (RSTO AL) failed: %06X" % ucode[0x20]
    for n in range(16):
        if n != 6:   # RN's slot is the CLRNH jump, not a display
            assert ucode[0x10 + n] == 0x003B10 | (n << 16), "RDISP check failed at %d" % n
    h = os.path.join(CSRC, "mbprom.h")
    c = os.path.join(CSRC, "mbprom.c")
    with open(h, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* mbprom.h - GENERATED by c_src/tools/gen_roms.py - do not edit. */\n"
                "#ifndef MBPROM_H\n#define MBPROM_H\n#include <stdint.h>\n"
                "extern const uint8_t  mb_map[32];     /* 136002-126.a1: write offset -> uPC */\n"
                "extern const uint32_t mb_ucode[256];  /* 136002-127..132: 24-bit microcode */\n"
                "#endif\n")
    with open(c, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* mbprom.c - GENERATED by c_src/tools/gen_roms.py from the Mathbox\n"
                " * PROMs 136002-126 (mapping) and 136002-127..132 (microcode) - do not edit.\n"
                " * Word layout: see mathbox.c. */\n#include \"mbprom.h\"\n\n")
        f.write("const uint8_t mb_map[32] = {\n")
        for i in range(0, 32, 8):
            f.write("    %s,\n" % ",".join("0x%02X" % b for b in mp[i:i + 8]))
        f.write("};\n\nconst uint32_t mb_ucode[256] = {\n")
        for i in range(0, 256, 8):
            f.write("    %s, /* uPC $%02X */\n" % (",".join("0x%06X" % w for w in ucode[i:i + 8]), i))
        f.write("};\n")
    print("wrote mbprom.c/.h (32-byte map, 256 microcode words)")


if __name__ == "__main__":
    main()
