/* allang.c - ALLANG ($D031-$D702): messages in English, French, German and
 * Spanish.  The tables (ENGMSG..SPAMSG, MSGLBS, the literals, LNGTAB,
 * TBLIFI, GAMLVS) are generated by tools/gen_allang.py into allang_data.c/.h
 * from the ROM image, cross-checked with the assembled listing - never typed.
 * The only code is INILIT.  Verified by tests/lockstep.exe (M4).
 */
#include "state.h"
#include "hw.h"
#include "game.h"
#include "allang_data.h"

/* INILIT ($D6BB): read the option switches - bonus life interval, coin
 * mode, lives per game, language pointer (LITRAL), option switch 3.
 * Exits X = the GAMLVS index, Y = the language index * 2 (GETOP3 keeps
 * both). */
xy6502 inilit(uint8_t x, uint8_t y)
{
    uint8_t a;
    unsigned c, c2;
    xy6502 r;
    (void)x; (void)y;
    a = hw_inop1();                                         /* LD6BB: bonus life interval */
    OPTIN2 = a;                                             /* LD6BE */
    a = (uint8_t)((a & 0x38) >> 3);                         /* LD6C0-LD6C4: AND / LSR x3 */
    c = 0;                                                  /*   the last LSR shifts out bit 2 of (a & $38) = 0 */
    x = a;                                                  /* LD6C5 */
    BLIFIN = allang_tblifi[x];                              /* LD6C6-LD6C9 (x <= 7) */
    S_CMODE = (uint8_t)(hw_inop0() ^ 0x02);                 /* LD6CC-LD6D1 */
    a = OPTIN2;                                             /* LD6D3: lives / game */
    for (int i = 0; i < 3; i++) {                           /* LD6D5-LD6D7 ROL x3 */
        c2 = (a & 0x80) ? 1u : 0u;
        a = (uint8_t)((a << 1) | c);
        c = c2;
    }
    x = (uint8_t)(a & 0x03);                                /* LD6D8-LD6DA */
    LVSGAM = allang_gamlvs[x];                              /* LD6DB-LD6DE */
    y = (uint8_t)(OPTIN2 & 0x06);                           /* LD6E1-LD6E5: language */
    LITRAL = (uint8_t)allang_lngtab[y >> 1];                /* LD6E6-LD6E9 LNGTAB,Y */
    g.ram[A_LITRAL + 1] = (uint8_t)(allang_lngtab[y >> 1] >> 8);   /* LD6EB-LD6EE LNGTAB+1,Y */
    a = (uint8_t)(allang_lngtab[y >> 1] >> 8);
    OPTIN3 = getop3(a, x, y);                               /* LD6F0-LD6F3 */
    r.x = x; r.y = y;
    return r;                                               /* LD6F6 */
}
