/* allang_data.h - GENERATED by c_src/tools/gen_allang.py from the ROM image
 * (cross-checked with the assembled listing) - do not edit.
 * ALLANG ($D031-$D702): message tables in four languages. */
#ifndef ALLANG_DATA_H
#define ALLANG_DATA_H
#include <stdint.h>

/* ---- ALLANG labels ---- */
#define ALLANG_ENGMSG   0xD031
#define ALLANG_FREMSG   0xD06D
#define ALLANG_GERMSG   0xD0A9
#define ALLANG_SPAMSG   0xD0E5
#define ALLANG_MSGLBS   0xD121
#define ALLANG_EGAMOV   0xD15D
#define ALLANG_FGAMOV   0xD167
#define ALLANG_GGAMOV   0xD175
#define ALLANG_SGAMOV   0xD17F
#define ALLANG_EPLAYR   0xD18F
#define ALLANG_EPLYR2   0xD18F
#define ALLANG_FPLAYR   0xD197
#define ALLANG_FPLYR2   0xD197
#define ALLANG_GPLAYR   0xD19F
#define ALLANG_GPLYR2   0xD19F
#define ALLANG_SPLAYR   0xD1A8
#define ALLANG_SPLYR2   0xD1A8
#define ALLANG_EPRESS   0xD1B1
#define ALLANG_FPRESS   0xD1BD
#define ALLANG_GPRESS   0xD1CF
#define ALLANG_SPRESS   0xD1DE
#define ALLANG_EPLAY    0xD1EB
#define ALLANG_FPLAY    0xD1F0
#define ALLANG_GPLAY    0xD1F6
#define ALLANG_SPLAY    0xD1FC
#define ALLANG_EENTER   0xD203
#define ALLANG_FENTER   0xD217
#define ALLANG_GENTER   0xD230
#define ALLANG_SENTER   0xD24D
#define ALLANG_EPRMOV   0xD261
#define ALLANG_FPRMOV   0xD275
#define ALLANG_GPRMOV   0xD294
#define ALLANG_SPRMOV   0xD2AE
#define ALLANG_EPRFIR   0xD2CB
#define ALLANG_FPRFIR   0xD2E0
#define ALLANG_GPRFIR   0xD2FB
#define ALLANG_SPRFIR   0xD316
#define ALLANG_EHIGHS   0xD333
#define ALLANG_FHIGHS   0xD33F
#define ALLANG_GHIGHS   0xD350
#define ALLANG_SHIGHS   0xD35E
#define ALLANG_ERANK    0xD366
#define ALLANG_FRANK    0xD379
#define ALLANG_GRANK    0xD38B
#define ALLANG_SRANK    0xD3A0
#define ALLANG_ERATE    0xD3B0
#define ALLANG_FRATE    0xD3BE
#define ALLANG_GRATE    0xD3CB
#define ALLANG_SRATE    0xD3DA
#define ALLANG_ENOVIC   0xD3E6
#define ALLANG_FNOVIC   0xD3E6
#define ALLANG_SNOVIC   0xD3ED
#define ALLANG_GNOVIC   0xD3F5
#define ALLANG_EEXPER   0xD3FF
#define ALLANG_FEXPER   0xD3FF
#define ALLANG_SEXPER   0xD406
#define ALLANG_GEXPER   0xD40E
#define ALLANG_EBONUS   0xD417
#define ALLANG_FBONUS   0xD417
#define ALLANG_GBONUS   0xD417
#define ALLANG_SBONUS   0xD417
#define ALLANG_ETIME    0xD41D
#define ALLANG_FTIME    0xD422
#define ALLANG_GTIME    0xD428
#define ALLANG_STIME    0xD42D
#define ALLANG_ELEVEL   0xD434
#define ALLANG_FLEVEL   0xD43A
#define ALLANG_GLEVEL   0xD441
#define ALLANG_SLEVEL   0xD446
#define ALLANG_EHOLE    0xD44C
#define ALLANG_FHOLE    0xD451
#define ALLANG_SHOLE    0xD456
#define ALLANG_GHOLE    0xD45B
#define ALLANG_EINSER   0xD460
#define ALLANG_FINSER   0xD46D
#define ALLANG_GINSER   0xD483
#define ALLANG_SINSER   0xD492
#define ALLANG_ECMODE   0xD4A1
#define ALLANG_FCMODE   0xD4A1
#define ALLANG_GCMODE   0xD4A1
#define ALLANG_SCMODE   0xD4A1
#define ALLANG_ECMOD1   0xD4AB
#define ALLANG_FCMOD1   0xD4BA
#define ALLANG_GCMOD1   0xD4CC
#define ALLANG_SCMOD1   0xD4DD
#define ALLANG_ECMOD2   0xD4EF
#define ALLANG_FCMOD2   0xD4FD
#define ALLANG_GCMOD2   0xD50E
#define ALLANG_SCMOD2   0xD51F
#define ALLANG_ECMOD3   0xD530
#define ALLANG_FCMOD3   0xD53F
#define ALLANG_GCMOD3   0xD551
#define ALLANG_SCMOD3   0xD563
#define ALLANG_EATARI   0xD575
#define ALLANG_FATARI   0xD575
#define ALLANG_GATARI   0xD575
#define ALLANG_SATARI   0xD575
#define ALLANG_ZATLIS   0xD575
#define ALLANG_ECREDI   0xD585
#define ALLANG_FCREDI   0xD585
#define ALLANG_ZATLIE   0xD585
#define ALLANG_GCREDI   0xD58E
#define ALLANG_SCREDI   0xD597
#define ALLANG_EBONPT   0xD5A1
#define ALLANG_FBONPT   0xD5A1
#define ALLANG_GBONPT   0xD5A1
#define ALLANG_SBONPT   0xD5A1
#define ALLANG_E2GAME   0xD5A8
#define ALLANG_F2GAME   0xD5B9
#define ALLANG_G2GAME   0xD5C8
#define ALLANG_S2GAME   0xD5D9
#define ALLANG_EBOLIF   0xD5E9
#define ALLANG_FBOLIF   0xD5F6
#define ALLANG_GBOLIF   0xD604
#define ALLANG_SBOLIF   0xD610
#define ALLANG_ESPIKE   0xD61C
#define ALLANG_FSPIKE   0xD629
#define ALLANG_GSPIKE   0xD63E
#define ALLANG_SSPIKE   0xD651
#define ALLANG_EAPROA   0xD662
#define ALLANG_FAPROA   0xD668
#define ALLANG_GAPROA   0xD66F
#define ALLANG_SAPROA   0xD674
#define ALLANG_ESUPZA   0xD67A
#define ALLANG_FSUPZA   0xD67A
#define ALLANG_GSUPZA   0xD68F
#define ALLANG_SSUPZA   0xD6A1
#define ALLANG_LNGTAB   0xD6B3
#define ALLANG_INILIT   0xD6BB
#define ALLANG_TBLIFI   0xD6F7
#define ALLANG_GAMLVS   0xD6FF

/* ---- ROM tables of other modules indexed by ALSCO2 ---- */
#define ROM_TCOMOD   0xA8B0
#define ROM_SCOSOL   0xA97D
#define ROM_IHALF    0xAAF3
#define ROM_SCOINI   0xAC08
#define ROM_HITRNK   0xAF6F
#define ROM_XPOTAB   0xB096
#define ROM_MSGTAB   0xB09B
#define ROM_BOXTAB   0xB0A3
#define ROM_ENDMSG   0xB0A3
#define ROM_SCALOC   0xCDDE
#define ROM_LIVLOC   0xCDE0
#define ROM_SCOLOC   0xCDE2
#define ROM_HISLOC   0xCDE4
#define ROM_HIILOC   0xCDE5
#define ROM_SCORES   0xCDE6
#define ROM_SCECOU   0xCE66
#define ROM_LEVEL    0x91FE
#define ROM_ZATC4S   0xAACE

#define ALLANG_NMSG 30  /* messages per language (message number = index * 2) */

extern const uint16_t allang_msgptr[4][ALLANG_NMSG];  /* ENGMSG, FREMSG, GERMSG, SPAMSG */
extern const uint8_t  allang_msglbs[2 * ALLANG_NMSG]; /* MSGLBS */
extern const uint16_t allang_lngtab[4];                /* LNGTAB */
extern const uint8_t  allang_tblifi[8];                /* TBLIFI */
extern const uint8_t  allang_gamlvs[4];                /* GAMLVS */

/* literals: signed X byte, then VGMSGA codes (index*2), bit 7 = last */
extern const uint8_t allang_lit_EGAMOV[10];
extern const uint8_t allang_lit_FGAMOV[14];
extern const uint8_t allang_lit_GGAMOV[10];
extern const uint8_t allang_lit_SGAMOV[16];
extern const uint8_t allang_lit_EPLAYR[8];
#define allang_lit_EPLYR2 allang_lit_EPLAYR
extern const uint8_t allang_lit_FPLAYR[8];
#define allang_lit_FPLYR2 allang_lit_FPLAYR
extern const uint8_t allang_lit_GPLAYR[9];
#define allang_lit_GPLYR2 allang_lit_GPLAYR
extern const uint8_t allang_lit_SPLAYR[9];
#define allang_lit_SPLYR2 allang_lit_SPLAYR
extern const uint8_t allang_lit_EPRESS[12];
extern const uint8_t allang_lit_FPRESS[18];
extern const uint8_t allang_lit_GPRESS[15];
extern const uint8_t allang_lit_SPRESS[13];
extern const uint8_t allang_lit_EPLAY[5];
extern const uint8_t allang_lit_FPLAY[6];
extern const uint8_t allang_lit_GPLAY[6];
extern const uint8_t allang_lit_SPLAY[7];
extern const uint8_t allang_lit_EENTER[20];
extern const uint8_t allang_lit_FENTER[25];
extern const uint8_t allang_lit_GENTER[29];
extern const uint8_t allang_lit_SENTER[20];
extern const uint8_t allang_lit_EPRMOV[20];
extern const uint8_t allang_lit_FPRMOV[31];
extern const uint8_t allang_lit_GPRMOV[26];
extern const uint8_t allang_lit_SPRMOV[29];
extern const uint8_t allang_lit_EPRFIR[21];
extern const uint8_t allang_lit_FPRFIR[27];
extern const uint8_t allang_lit_GPRFIR[27];
extern const uint8_t allang_lit_SPRFIR[29];
extern const uint8_t allang_lit_EHIGHS[12];
extern const uint8_t allang_lit_FHIGHS[17];
extern const uint8_t allang_lit_GHIGHS[14];
extern const uint8_t allang_lit_SHIGHS[8];
extern const uint8_t allang_lit_ERANK[19];
extern const uint8_t allang_lit_FRANK[18];
extern const uint8_t allang_lit_GRANK[21];
extern const uint8_t allang_lit_SRANK[16];
extern const uint8_t allang_lit_ERATE[14];
extern const uint8_t allang_lit_FRATE[13];
extern const uint8_t allang_lit_GRATE[15];
extern const uint8_t allang_lit_SRATE[12];
extern const uint8_t allang_lit_ENOVIC[7];
#define allang_lit_FNOVIC allang_lit_ENOVIC
extern const uint8_t allang_lit_SNOVIC[8];
extern const uint8_t allang_lit_GNOVIC[10];
extern const uint8_t allang_lit_EEXPER[7];
#define allang_lit_FEXPER allang_lit_EEXPER
extern const uint8_t allang_lit_SEXPER[8];
extern const uint8_t allang_lit_GEXPER[9];
extern const uint8_t allang_lit_EBONUS[6];
#define allang_lit_FBONUS allang_lit_EBONUS
#define allang_lit_GBONUS allang_lit_EBONUS
#define allang_lit_SBONUS allang_lit_EBONUS
extern const uint8_t allang_lit_ETIME[5];
extern const uint8_t allang_lit_FTIME[6];
extern const uint8_t allang_lit_GTIME[5];
extern const uint8_t allang_lit_STIME[7];
extern const uint8_t allang_lit_ELEVEL[6];
extern const uint8_t allang_lit_FLEVEL[7];
extern const uint8_t allang_lit_GLEVEL[5];
extern const uint8_t allang_lit_SLEVEL[6];
extern const uint8_t allang_lit_EHOLE[5];
extern const uint8_t allang_lit_FHOLE[5];
extern const uint8_t allang_lit_SHOLE[5];
extern const uint8_t allang_lit_GHOLE[5];
extern const uint8_t allang_lit_EINSER[13];
extern const uint8_t allang_lit_FINSER[22];
extern const uint8_t allang_lit_GINSER[15];
extern const uint8_t allang_lit_SINSER[15];
extern const uint8_t allang_lit_ECMODE[10];
#define allang_lit_FCMODE allang_lit_ECMODE
#define allang_lit_GCMODE allang_lit_ECMODE
#define allang_lit_SCMODE allang_lit_ECMODE
extern const uint8_t allang_lit_ECMOD1[15];
extern const uint8_t allang_lit_FCMOD1[18];
extern const uint8_t allang_lit_GCMOD1[17];
extern const uint8_t allang_lit_SCMOD1[18];
extern const uint8_t allang_lit_ECMOD2[14];
extern const uint8_t allang_lit_FCMOD2[17];
extern const uint8_t allang_lit_GCMOD2[17];
extern const uint8_t allang_lit_SCMOD2[17];
extern const uint8_t allang_lit_ECMOD3[15];
extern const uint8_t allang_lit_FCMOD3[18];
extern const uint8_t allang_lit_GCMOD3[18];
extern const uint8_t allang_lit_SCMOD3[18];
extern const uint8_t allang_lit_EATARI[16];
#define allang_lit_FATARI allang_lit_EATARI
#define allang_lit_GATARI allang_lit_EATARI
#define allang_lit_SATARI allang_lit_EATARI
#define allang_lit_ZATLIS allang_lit_EATARI
extern const uint8_t allang_lit_ECREDI[9];
#define allang_lit_FCREDI allang_lit_ECREDI
#define allang_lit_ZATLIE allang_lit_ECREDI
extern const uint8_t allang_lit_GCREDI[9];
extern const uint8_t allang_lit_SCREDI[10];
extern const uint8_t allang_lit_EBONPT[7];
#define allang_lit_FBONPT allang_lit_EBONPT
#define allang_lit_GBONPT allang_lit_EBONPT
#define allang_lit_SBONPT allang_lit_EBONPT
extern const uint8_t allang_lit_E2GAME[17];
extern const uint8_t allang_lit_F2GAME[15];
extern const uint8_t allang_lit_G2GAME[17];
extern const uint8_t allang_lit_S2GAME[16];
extern const uint8_t allang_lit_EBOLIF[13];
extern const uint8_t allang_lit_FBOLIF[14];
extern const uint8_t allang_lit_GBOLIF[12];
extern const uint8_t allang_lit_SBOLIF[12];
extern const uint8_t allang_lit_ESPIKE[13];
extern const uint8_t allang_lit_FSPIKE[21];
extern const uint8_t allang_lit_GSPIKE[19];
extern const uint8_t allang_lit_SSPIKE[17];
extern const uint8_t allang_lit_EAPROA[6];
extern const uint8_t allang_lit_FAPROA[7];
extern const uint8_t allang_lit_GAPROA[5];
extern const uint8_t allang_lit_SAPROA[6];
extern const uint8_t allang_lit_ESUPZA[21];
#define allang_lit_FSUPZA allang_lit_ESUPZA
extern const uint8_t allang_lit_GSUPZA[18];
extern const uint8_t allang_lit_SSUPZA[18];

#endif
