/* altes2_data.h - GENERATED by c_src/tools/gen_altes2.py from the ROM image
 * (cross-checked with the assembled listing, symbols.json, program_refs.json,
 * the vector-ROM listing and the defines) - do not edit.
 * ALTES2 ($D7E1-$DDDC, $DFDC-$DFF7) label addresses; table bytes are read
 * with cpu_rd().  Self-test ROM checksums of rev 3 (dump and progrom/vecrom):
 * 00 00 00 00 00 00 00 00 00 00 00 00 (all 0). */
#ifndef ALTES2_DATA_H
#define ALTES2_DATA_H

/* ---- ALTES2 labels (code and data; * = program_refs.json routine header) ---- */
#define ALTES2_SYSTEM     0xD7E1  /* code * */
#define ALTES2_DSPSYS     0xD804  /* code * */
#define ALTES2_POSDIG     0xD8A9  /* code * */
#define ALTES2_OPTMSK     0xD8B6  /* data */
#define ALTES2_CRMECHT    0xD8BA  /* data */
#define ALTES2_BONADR     0xD8C2  /* data */
#define ALTES2_HIBAD      0xD8CA  /* code * */
#define ALTES2_BRAMREP    0xD8CD  /* code */
#define ALTES2_HIRBAD     0xD92F  /* code * */
#define ALTES2_HIRBD2     0xD931  /* code */
#define ALTES2_RESET      0xD93F  /* code * */
#define ALTES2_SFTEST     0xD93F  /* code */
#define ALTES2_JMPHIB     0xD9B9  /* code */
#define ALTES2_ROMTST     0xDA0A  /* code */
#define ALTES2_OK1        0xDA53  /* code */
#define ALTES2_OK2        0xDA62  /* code */
#define ALTES2_TIMEST     0xDAA9  /* code */
#define ALTES2_WDGTST     0xDAF7  /* code */
#define ALTES2_TABCOL     0xDAF9  /* data */
#define ALTES2_SFTJSR     0xDB01  /* data */
#define ALTES2_SFTJSE     0xDB0F  /* code * */
#define ALTES2_SSTATE     0xDB0F  /* code */
#define ALTES2_NOOPR_DB21 0xDB21  /* code * */
#define ALTES2_SIGANA     0xDB22  /* code * */
#define ALTES2_BADEAR     0xDB5A  /* code * */
#define ALTES2_SCHEKR     0xDB6F  /* code * */
#define ALTES2_SINTEN     0xDB7E  /* code * */
#define ALTES2_SHATCH     0xDB84  /* code * */
#define ALTES2_JSRVGJ     0xDB88  /* code */
#define ALTES2_NOSOUN     0xDB8B  /* code */
#define ALTES2_SHYSTER    0xDB9A  /* code * */
#define ALTES2_SNDTBL     0xDBD6  /* data */
#define ALTES2_GETOP3     0xDBE0  /* code * */
#define ALTES2_ROMREP     0xDBF7  /* code * */
#define ALTES2_BADBOX     0xDC15  /* code */
#define ALTES2_BADNWS     0xDCE1  /* data */
#define ALTES2_READMB     0xDCE6  /* code * */
#define ALTES2_TOOSLO     0xDD0C  /* code */
#define ALTES2_DOPSWI     0xDD0D  /* code * */
#define ALTES2_BITS2      0xDD27  /* code * */
#define ALTES2_BITS3      0xDD29  /* code * */
#define ALTES2_GENOPD     0xDD2B  /* code * */
#define ALTES2_DBOOKE     0xDD41  /* code * */
#define ALTES2_CHKSMB     0xDDDC  /* data */
#define ALTES2_SNDFRQ     0xDFDC  /* data */
#define ALTES2_POTYTA     0xDFE4  /* data */
#define ALTES2_POTXTA     0xDFE8  /* data */
#define ALTES2_SNDTBL_M1  0xDBD5  /* SNDTBL-1: the underflow byte read with X = 0 */

/* ---- unlabeled loop heads ---- */
#define ALTES2_ZPTEST     0xD9A9  /* zero-page march (RESET, TEST closed) */
#define ALTES2_RAMTST     0xD9D6  /* pages $01-$07, $20-$2F */
#define ALTES2_DIAGLP     0xDA8D  /* diagnostic loop head (one diag_pass() per visit) */

/* SFTJSR entries (QSTATE / 2): BADEAR ROMREP SHATCH SHYSTER SINTEN SCHEKR SIGANA */
#define ALTES2_SFTJSR_N 7
/* ROMTST's LDA #<[PROG/$100] operand ($DA2F): first program-ROM page */
#define ALTES2_PROG_PAGE 0x90

/* ---- vector-ROM pictures / tables ALTES2 draws or indexes ---- */
#define ROM_SYSOPT   0x3F16
#define ROM_LIFEY    0x326C
#define ROM_EASING   0x346E
#define ROM_COCMSG   0x3482
#define ROM_ROMRPI   0x3492
#define ROM_BOKLIT   0x3DCE
#define ROM_HATCH    0x330A
#define ROM_INTEST   0x32B6
#define ROM_CHEKER   0x334E
#define ROM_HYSTER   0x3456
#define ROM_VORBOX   0x34AA
#define ROM_BONDRY   0x34A6
#define ROM_VGMSGA   0x31E4

#endif
