/* mbprom.h - GENERATED by c_src/tools/gen_roms.py - do not edit. */
#ifndef MBPROM_H
#define MBPROM_H
#include <stdint.h>
extern const uint8_t  mb_map[32];     /* 136002-126.a1: write offset -> uPC */
extern const uint32_t mb_ucode[256];  /* 136002-127..132: 24-bit microcode */
#endif
