/* progrom.h - GENERATED by c_src/tools/gen_roms.py - do not edit. */
#ifndef PROGROM_H
#define PROGROM_H
#include <stdint.h>
#define PROGROM_BASE 0x9000
#define PROGROM_SIZE 0x5000
extern const uint8_t progrom[0x5000]; /* program ROM (rev 3) */
#endif
