/* state_defs.h - GENERATED by c_src/tools/gen_state.py from
 * ../disasm/tempest_defines.asm - do not edit by hand.
 *
 * A_NAME = CPU address of an alias.  NAME = the RAM cell as an lvalue
 * (variable sections only).  K_NAME = a Constants-section value.
 * Vector RAM: VRAM(A_NAME + i).  Hardware: hw_* (hw.h). */

#ifndef STATE_DEFS_H
#define STATE_DEFS_H

/* ---- Memory map ---- */
#define A_ZeroPageRam  0x0000  /* Through $00FF. Control, work, player and display variables. */
#define A_PageOneRam   0x0100  /* Through $01FF. Game variables; the 6502 stack grows down from $01FF (the IRQ requires SP >= $D0). */
#define A_GameRam      0x0200  /* Through $07FF. Object tables, explosions, enemy lines, high scores. */
#define A_ColorRam     0x0800  /* Through $080F. 16 colour entries, 4 bits active low: b0 red-low, b1 red, b2 blue, b3 green. */
#define A_VectorRam    0x2000  /* Through $2FFF. AVG display lists (sub-buffers, see Vector RAM below). */
#define A_VectorRom    0x3000  /* Through $3FFF. Characters and pictures (tempest_vector_rom.asm). */
#define A_AuxBoardIo   0x6000  /* EAROM, Mathbox, two POKEYs, LED/flip latch (HARDWA). */
#define A_ProgramRom   0x9000  /* Through $DFFF (tempest_program_rom.asm); vectors at $DFFA. */
#define A_RomMirror    0xE000  /* Through $FFFF. Mirror of the top program ROM; the 6502 reads its vectors here. */

/* ---- Hardware registers ---- */
#define A_COLPORT      0x0800  /* COLOR RAM. Colour RAM $0800-$080F (write): 16 entries, 4 bits active low (b0 red-low, b1 red, b2 blue, b3 green). */
#define A_IN1          0x0C00  /* INPUT BYTE 1. Read: b0 right coin, b1 centre coin, b2 left coin, b3 slam, b4 self test, b5 diag step, b6 VG HALT (1 = done), b7 3 kHz clock. */
#define A_INOP0        0x0D00  /* OPTION SWITCH 0. Read: option switches N13 (coinage). */
#define A_INOP1        0x0E00  /* OPTION SWITCH 1. Read: option switches L12 (minimum credits, language, bonus life, lives). */
#define A_OUT0         0x4000  /* OUTPUT BYTE 0. Write: b0 right coin counter, b1 centre, b2 left, b3 invert X (flip), b4 invert Y. */
#define A_VGSTART      0x4800  /* VG START. Write: start the AVG at vector RAM $2000. */
#define A_WTCHDG       0x5000  /* WATCH DOG CLEAR. Write: watchdog clear (the IRQ does it only while the software watchdog is happy). */
#define A_INTACK       0x5000  /* Same address as WTCHDG: the write also acknowledges the IRQ. */
#define A_VGSTOP       0x5800  /* VG RESET. Write: reset (halt) the AVG. */
#define A_HARDWA       0x6000  /* AUX BOARD IO BASE ADDRESS. Auxiliary board I/O base. */
#define A_EADAL        0x6000  /* EAROM WRITE BASE ADDRESS. Write $6000-$603F: EAROM address = offset, data = value latched for the next write. */
#define A_EACTL        0x6040  /* EAROM CONTROL. Write: EAROM control (EACK clock, EAC2, EAC1 inverted, EACE chip select). */
#define A_MSTAT        0x6040  /* STATUS. Read: Mathbox status, D7 = 1 while busy. */
#define A_EAIN         0x6050  /* EAROM READ PORT. Read: EAROM data. */
#define A_MYLOW        0x6060  /* READ LOW. Read: Mathbox result low byte. */
#define A_MYHIGH       0x6070  /* READ HIGH. Read: Mathbox result high byte. */
#define A_MBSTAR       0x6080  /* START (SIGNS ANALYSIS). Write $6080-$609F: Mathbox register load / function start (MAL..MDYPL below). */
#define A_MAL          0x6080
#define A_MAH          0x6081
#define A_MBL          0x6082
#define A_MBH          0x6083
#define A_MEL          0x6084
#define A_MEH          0x6085
#define A_MFL          0x6086
#define A_MFH          0x6087
#define A_MXL          0x6088
#define A_MXH          0x6089
#define A_MNL          0x608C
#define A_MZLL         0x608D
#define A_MZLH         0x608E
#define A_MZHL         0x608F
#define A_MZHH         0x6090
#define A_SYM          0x6092
#define A_MSZXD        0x6094
#define A_MXPL         0x6095
#define A_MXPH         0x6096
#define A_MDYPL        0x6098
#define A_POKEY        0x60C0  /* POKEY 1 ($60C0-$60CF): sound channels 1-4, spinner and cocktail input. */
#define A_AUDF1        0x60C0
#define A_AUDC1        0x60C1
#define A_AUDCTL       0x60C8
#define A_ALLPOT       0x60C8  /* POKEY 1 read: b0-b3 spinner (4-bit position), b4 cocktail. (Write: AUDCTL.) */
#define A_RANDOM       0x60CA  /* POKEY 1 read: random number (also used by the POKEY protection checks). */
#define A_POTGO        0x60CB  /* POKEY 1 write: start pot scan. */
#define A_SKCTL        0x60CF  /* POKEY 1 serial/keyboard control. */
#define A_POKEY2       0x60D0  /* POKEY 2 ($60D0-$60DF): sound channels 5-8 and buttons. */
#define A_AUDF2        0x60D0
#define A_AUDC2        0x60D1
#define A_AUD2CTL      0x60D8
#define A_ALLPO2       0x60D8  /* POKEY 2 read: b0-b1 difficulty, b2 rating, b3 superzapper, b4 fire, b5 start 1, b6 start 2. (Write: AUD2CTL.) */
#define A_RANDO2       0x60DA  /* POKEY 2 read: random number. */
#define A_POTGO2       0x60DB  /* POKEY 2 write: start pot scan. */
#define A_SKCTL2       0x60DF  /* POKEY 2 serial/keyboard control. */
#define A_OUTANK       0x60E0  /* OUTPUT BYTE 1. Write: b0 LED 2 (MLED2), b1 LED 1 (MLED1), b2 flip (MFLIP); LEDs active low. */

/* ---- Zero page variables ---- */
#define A_QSTATE       0x0000  /* CONTAINS CODE FOR STATE ROUTINE (INDEX INTO ROUTAD) */
#define QSTATE         (g.ram[A_QSTATE])
#define A_QDSTATE      0x0001  /* DISPLAY STATE */
#define QDSTATE        (g.ram[A_QDSTATE])
#define A_QNXTSTA      0x0002  /* NEXT STATE CODE TO EXECUTE AFTER PAUSE */
#define QNXTSTA        (g.ram[A_QNXTSTA])
#define A_QFRAME       0x0003  /* FRAME COUNTER (WRAPS AT FF) */
#define QFRAME         (g.ram[A_QFRAME])
#define A_QTMPAUS      0x0004  /* PAUSE TIMER (IN SECOND UNITS) */
#define QTMPAUS        (g.ram[A_QTMPAUS])
#define A_QSTATUS      0x0005  /* STATUS FLAGS */
#define QSTATUS        (g.ram[A_QSTATUS])
#define A_S_S_CRDT     0x0006  /* # OF CREDITS */
#define S_S_CRDT       (g.ram[A_S_S_CRDT])
#define A_S_INTCT      0x0007  /* INTERRUPT COUNT */
#define S_INTCT        (g.ram[A_S_INTCT])
#define A_S_TEST       0x0008
#define S_TEST         (g.ram[A_S_TEST])
#define A_S_LAM        0x0008
#define S_LAM          (g.ram[A_S_LAM])
#define A_S_COINA      0x0008  /* COIN MECHS */
#define S_COINA        (g.ram[A_S_COINA])
#define A_S_CMODE      0x0009
#define S_CMODE        (g.ram[A_S_CMODE])
#define A_OPTIN1       0x0009  /* OPTIONS */
#define OPTIN1         (g.ram[A_OPTIN1])
#define A_OPTIN2       0x000A
#define OPTIN2         (g.ram[A_OPTIN2])
#define A_TSLAMR       0x000B  /* SLAM SOUND TIMER */
#define TSLAMR         (g.ram[A_TSLAMR])
#define A_S_LMTIM      0x000C  /* SLAM INDICATION */
#define S_LMTIM        (g.ram[A_S_LMTIM])
#define A_S_CNSTT      0x000D
#define S_CNSTT        (g.ram[A_S_CNSTT])
#define A_S_PSTSL      0x0010
#define S_PSTSL        (g.ram[A_S_PSTSL])
#define A_S_CCTIM      0x0013
#define S_CCTIM        (g.ram[A_S_CCTIM])
#define A_S_BCCNT      0x0016
#define S_BCCNT        (g.ram[A_S_BCCNT])
#define A_S_CNCT       0x0017
#define S_CNCT         (g.ram[A_S_CNCT])
#define A_S_BC         0x0018
#define S_BC           (g.ram[A_S_BC])
#define A_COLRAM       0x0019  /* COLOR RAM */
#define COLRAM         (g.ram[A_COLRAM])
#define A_TEMP0        0x0029
#define TEMP0          (g.ram[A_TEMP0])
#define A_TEMP1        0x002A
#define TEMP1          (g.ram[A_TEMP1])
#define A_TEMPL        0x002A
#define TEMPL          (g.ram[A_TEMPL])
#define A_TEMP2        0x002B
#define TEMP2          (g.ram[A_TEMP2])
#define A_TEMP3        0x002C
#define TEMP3          (g.ram[A_TEMP3])
#define A_TEMP4        0x002D
#define TEMP4          (g.ram[A_TEMP4])
#define A_TEMPX        0x002E
#define TEMPX          (g.ram[A_TEMPX])
#define A_TEMPY        0x002F
#define TEMPY          (g.ram[A_TEMPY])
#define A_TEMPZ        0x0030
#define TEMPZ          (g.ram[A_TEMPZ])
#define A_MTEMP        0x0031  /* MACRO USE ONLY */
#define MTEMP          (g.ram[A_MTEMP])
#define A_SAVEX        0x0035
#define SAVEX          (g.ram[A_SAVEX])
#define A_SAVEY        0x0036
#define SAVEY          (g.ram[A_SAVEY])
#define A_INDEX1       0x0037
#define INDEX1         (g.ram[A_INDEX1])
#define A_INDEX2       0x0038
#define INDEX2         (g.ram[A_INDEX2])
#define A_INDEX3       0x0039
#define INDEX3         (g.ram[A_INDEX3])
#define A_INDEX4       0x003A
#define INDEX4         (g.ram[A_INDEX4])
#define A_INDYLO       0x003B  /* USE FOR INDIRECT Y */
#define INDYLO         (g.ram[A_INDYLO])
#define A_INDYHI       0x003C
#define INDYHI         (g.ram[A_INDYHI])
#define A_PLAYUP       0x003D  /* PLAYER UP (0=LEFT, 1=RIGHT) */
#define PLAYUP         (g.ram[A_PLAYUP])
#define A_NUMPLA       0x003E  /* # OF PLAYERS (-1) */
#define NUMPLA         (g.ram[A_NUMPLA])
#define A_NEWPLA       0x003F  /* # OF NEXT PLAYER (FROM END WAVE TO NEW WAVE) */
#define NEWPLA         (g.ram[A_NEWPLA])
#define A_LSCORL       0x0040  /* SCORE ARRAY */
#define LSCORL         (g.ram[A_LSCORL])
#define A_LSCORM       0x0041  /* (TRIPLE PRECISION BCD) */
#define LSCORM         (g.ram[A_LSCORM])
#define A_LSCORH       0x0042
#define LSCORH         (g.ram[A_LSCORH])
#define A_RSCORL       0x0043
#define RSCORL         (g.ram[A_RSCORL])
#define A_RSCORM       0x0044
#define RSCORM         (g.ram[A_RSCORM])
#define A_RSCORH       0x0045
#define RSCORH         (g.ram[A_RSCORH])
#define A_WAVEN1       0x0046  /* # OF ENEMY WAVE WHICH PLAYER IS BATTLING -1 */
#define WAVEN1         (g.ram[A_WAVEN1])
#define A_WAVEN2       0x0047
#define WAVEN2         (g.ram[A_WAVEN2])
#define A_LIVES1       0x0048  /* # OF BASES PLAYER HAS LEFT */
#define LIVES1         (g.ram[A_LIVES1])
#define A_LIVES2       0x0049
#define LIVES2         (g.ram[A_LIVES2])
#define A_INPUT        0x004A  /* ROUGH INPUT (0=ON) */
#define INPUT          (g.ram[A_INPUT])
#define A_DBSW         0x004C  /* LAST ROUGH INPUT (0=ON) */
#define DBSW           (g.ram[A_DBSW])
#define A_SWSTRT       0x004D
#define SWSTRT         (g.ram[A_SWSTRT])
#define A_SWSTAT       0x004D  /* DEBOUNCED INPUT (0=ON) */
#define SWSTAT         (g.ram[A_SWSTAT])
#define A_SWFINA       0x004E  /* LATCHED INPUT (1=ON)(CLEARED BY GAME) */
#define SWFINA         (g.ram[A_SWFINA])
#define A_SWRELE       0x004F  /* OLD SWSTAT READING */
#define SWRELE         (g.ram[A_SWRELE])
#define A_TBHD         0x0050  /* TRACK BALL VARIABLES */
#define TBHD           (g.ram[A_TBHD])
#define A_CURSPO       0x0051
#define CURSPO         (g.ram[A_CURSPO])
#define A_OTB          0x0052
#define OTB            (g.ram[A_OTB])
#define A_FRTIMR       0x0053  /* VG FRAME DISPLAY TIMER */
#define FRTIMR         (g.ram[A_FRTIMR])
#define A_BUFRDY       0x0054  /* BUFFER STATUS (0-DISPLAY IT, <>0:BUILD IT) */
#define BUFRDY         (g.ram[A_BUFRDY])
#define A_OBJIND       0x0055  /* INDEX INTO OBJECT ARRAYS (OCNT....) */
#define OBJIND         (g.ram[A_OBJIND])
#define A_PXL          0x0056  /* TEMP STORAGE FOR POINT'S COORDINATES */
#define PXL            (g.ram[A_PXL])
#define A_PYL          0x0057  /* (WORLD) */
#define PYL            (g.ram[A_PYL])
#define A_PZL          0x0058
#define PZL            (g.ram[A_PZL])
#define A_LINSCA       0x0059  /* LINEAR SCALE (W3DSUP) */
#define LINSCA         (g.ram[A_LINSCA])
#define A_BINSCA       0x005A  /* BINARY SCALE (W3DSUP) */
#define BINSCA         (g.ram[A_BINSCA])
#define A_EYH          0x005B  /* EYE POSITION (SIGNED) HI BYTE */
#define EYH            (g.ram[A_EYH])
#define A_EYLL         0x005C  /* EYE POSITION (FRACTIONAL) */
#define EYLL           (g.ram[A_EYLL])
#define A_EYLDES       0x005D  /* EYE DESTINATION Y */
#define EYLDES         (g.ram[A_EYLDES])
#define A_EXL          0x005E  /* LOCATION OF EYE (WORLD COORD) */
#define EXL            (g.ram[A_EXL])
#define A_EYL          0x005F
#define EYL            (g.ram[A_EYL])
#define A_EZL          0x0060
#define EZL            (g.ram[A_EZL])
#define A_SXL          0x0061  /* TEMP STORAGE FOR POINT'S COORD */
#define SXL            (g.ram[A_SXL])
#define A_SXH          0x0062  /* (SCREEN) */
#define SXH            (g.ram[A_SXH])
#define A_SZL          0x0063
#define SZL            (g.ram[A_SZL])
#define A_SZH          0x0064
#define SZH            (g.ram[A_SZH])
#define A_EYEFAC       0x0065  /* EYE SCREEN DISTANCE */
#define EYEFAC         (g.ram[A_EYEFAC])
#define A_XADJL        0x0066
#define XADJL          (g.ram[A_XADJL])
#define A_ZADJL        0x0068  /* SCREEN Z VANISH PT */
#define ZADJL          (g.ram[A_ZADJL])
#define A_CURNTX       0x006A  /* CURRENT BEAM POSITION */
#define CURNTX         (g.ram[A_CURNTX])
#define A_CURNTY       0x006C
#define CURNTY         (g.ram[A_CURNTY])
#define A_XCOMP        0x006E  /* X COMPONENT FOR VECTOR DELTA */
#define XCOMP          (g.ram[A_XCOMP])
#define A_YCOMP        0x0070
#define YCOMP          (g.ram[A_YCOMP])
#define A_VGSIZE       0x0072  /* SCALING SIZE */
#define VGSIZE         (g.ram[A_VGSIZE])
#define A_VGBRIT       0x0073  /* VECTOR BRIGHTNESS */
#define VGBRIT         (g.ram[A_VGBRIT])
#define A_VGLIST       0x0074  /* VECTOR LIST POINTER */
#define VGLIST         (g.ram[A_VGLIST])
#define A_SVGLIST      0x0076
#define SVGLIST        (g.ram[A_SVGLIST])
#define A_X0L          0x0078  /* USED WITHIN ONELIN IN ALDISP TO */
#define X0L            (g.ram[A_X0L])
#define A_BFACTR       0x0078  /* USED IN SCAPIC - BINARY PART OF SCALE FACTOR */
#define BFACTR         (g.ram[A_BFACTR])
#define A_X1L          0x0079  /* STORE UNIT VECTORS X 0>7 (X AND Z) */
#define X1L            (g.ram[A_X1L])
#define A_SCFL         0x0079  /* USED IN SCAPIC - SCALE FACTOR */
#define SCFL           (g.ram[A_SCFL])
#define A_X2L          0x007A
#define X2L            (g.ram[A_X2L])
#define A_X3L          0x007B
#define X3L            (g.ram[A_X3L])
#define A_LEFSID       0x007B  /* REQUEST RATE DISPLAY LEFT SIDE */
#define LEFSID         (g.ram[A_LEFSID])
#define A_X4L          0x007C
#define X4L            (g.ram[A_X4L])
#define A_RITSID       0x007C  /* RRD-RIGHT SIDE */
#define RITSID         (g.ram[A_RITSID])
#define A_X5L          0x007D
#define X5L            (g.ram[A_X5L])
#define A_X6L          0x007E
#define X6L            (g.ram[A_X6L])
#define A_X7L          0x007F
#define X7L            (g.ram[A_X7L])
#define A_X0H          0x0080
#define X0H            (g.ram[A_X0H])
#define A_X1H          0x0081
#define X1H            (g.ram[A_X1H])
#define A_X2H          0x0082
#define X2H            (g.ram[A_X2H])
#define A_X3H          0x0083
#define X3H            (g.ram[A_X3H])
#define A_X4H          0x0084
#define X4H            (g.ram[A_X4H])
#define A_X5H          0x0085
#define X5H            (g.ram[A_X5H])
#define A_X6H          0x0086
#define X6H            (g.ram[A_X6H])
#define A_X7H          0x0087
#define X7H            (g.ram[A_X7H])
#define A_Z0L          0x0088
#define Z0L            (g.ram[A_Z0L])
#define A_Z1L          0x0089
#define Z1L            (g.ram[A_Z1L])
#define A_Z2L          0x008A
#define Z2L            (g.ram[A_Z2L])
#define A_Z3L          0x008B
#define Z3L            (g.ram[A_Z3L])
#define A_Z4L          0x008C
#define Z4L            (g.ram[A_Z4L])
#define A_Z5L          0x008D
#define Z5L            (g.ram[A_Z5L])
#define A_Z6L          0x008E
#define Z6L            (g.ram[A_Z6L])
#define A_Z7L          0x008F
#define Z7L            (g.ram[A_Z7L])
#define A_Z0H          0x0090
#define Z0H            (g.ram[A_Z0H])
#define A_Z1H          0x0091
#define Z1H            (g.ram[A_Z1H])
#define A_Z2H          0x0092
#define Z2H            (g.ram[A_Z2H])
#define A_Z3H          0x0093
#define Z3H            (g.ram[A_Z3H])
#define A_Z4H          0x0094
#define Z4H            (g.ram[A_Z4H])
#define A_Z5H          0x0095
#define Z5H            (g.ram[A_Z5H])
#define A_Z6H          0x0096
#define Z6H            (g.ram[A_Z6H])
#define A_Z7H          0x0097
#define Z7H            (g.ram[A_Z7H])
#define A_INTENS       0x0098  /* OBJECT INTENSITY (D7-D5) */
#define INTENS         (g.ram[A_INTENS])
#define A_SUBCOU       0x0099  /* POINT COUNTER */
#define SUBCOU         (g.ram[A_SUBCOU])
#define A_UNITXL       0x009A  /* UNIT VECTORS */
#define UNITXL         (g.ram[A_UNITXL])
#define A_UNITXH       0x009B
#define UNITXH         (g.ram[A_UNITXH])
#define A_UNITZL       0x009C
#define UNITZL         (g.ram[A_UNITZL])
#define A_UNITZH       0x009D
#define UNITZH         (g.ram[A_UNITZH])
#define A_COLOR        0x009E
#define COLOR          (g.ram[A_COLOR])
#define A_CURWAV       0x009F  /* CURRENT WAVE */
#define CURWAV         (g.ram[A_CURWAV])
#define A_YDEUNI       0x00A0  /* Y DELTA FOR UNIT SCALE */
#define YDEUNI         (g.ram[A_YDEUNI])
#define A_TNKOUT       0x00A1  /* START LEDS, ETC. FOR DUTANK */
#define TNKOUT         (g.ram[A_TNKOUT])
#define A_TCMFLG       0x00A2  /* 2 GAME MIN FLAG (80=NOT 2 YET) */
#define TCMFLG         (g.ram[A_TCMFLG])
#define A_NEWAIT       0x00A3
#define NEWAIT         (g.ram[A_NEWAIT])
#define A_OFRTIM       0x00A4
#define OFRTIM         (g.ram[A_OFRTIM])
#define A_OCURSL       0x00A5  /* OLD CURSOR POSITION (LINE #) */
#define OCURSL         (g.ram[A_OCURSL])
#define A_ESHCOU       0x00A6  /* ENEMY SOT COUNT */
#define ESHCOU         (g.ram[A_ESHCOU])
#define A_CHACHA       0x00A7  /* CHARGE CHARGE DELTA */
#define CHACHA         (g.ram[A_CHACHA])
#define A_CHAINV       0x00A8  /* CHARGE INVADER DELTA */
#define CHAINV         (g.ram[A_CHAINV])
#define A_VGY          0x00A9  /* INDEX INTO VGLIST */
#define VGY            (g.ram[A_VGY])
#define A_OLDLLO       0x00AA  /* OLD ENEMY LINE BUFFER START ADDRESS */
#define OLDLLO         (g.ram[A_OLDLLO])
#define A_OLDLHI       0x00AB
#define OLDLHI         (g.ram[A_OLDLHI])
#define A_LITRAL       0x00AC  /* LANGUAGE TABLE */
#define LITRAL         (g.ram[A_LITRAL])
#define A_ZPNLOC       0x00AE  /* USED BY DIGITS */
#define ZPNLOC         (g.ram[A_ZPNLOC])
#define A_ZPOFFS       0x00AF  /* USED BY DIGITS */
#define ZPOFFS         (g.ram[A_ZPOFFS])
#define A_RUNGVG       0x00B0  /* RUNG VG PTR. */
#define RUNGVG         (g.ram[A_RUNGVG])
#define A_PUCHDE       0x00B2  /* PULSAR CHASE DELAY (# FRAMES BEFORE FLIP) */
#define PUCHDE         (g.ram[A_PUCHDE])
#define A_WTTFRA       0x00B3  /* # OF FLIP SECTIONS TO TAKE/FRAME FOR TOP FLIPPERS */
#define WTTFRA         (g.ram[A_WTTFRA])
#define A_TOUT0        0x00B4  /* SCREEN FLIP STATUS FOR IO */
#define TOUT0          (g.ram[A_TOUT0])
#define A_QT1          0x00B5  /* SECURITY */
#define QT1            (g.ram[A_QT1])
#define A_SECUVG       0x00B6  /* SECURITY PTR. */
#define SECUVG         (g.ram[A_SECUVG])
#define A_EASRCE       0x00BD  /* RAM POINTER */
#define EASRCE         (g.ram[A_EASRCE])
#define A_SINDEX       0x00BF
#define SINDEX         (g.ram[A_SINDEX])
#define A_POINT        0x00C0  /* POINTER OFFSET INTO DATA TABLES(IF 0, CHANNEL NOT ACTIVE) */
#define POINT          (g.ram[A_POINT])
#define A_CURRENT      0x00D0  /* OUTPUT VALUE */
#define CURRENT        (g.ram[A_CURRENT])
#define A_FRAMES       0x00E0  /* FRAMES UNTIL NEXT CHANGE */
#define FRAMES         (g.ram[A_FRAMES])
#define A_COUNT        0x00F0  /* COUNT OF TOTAL CHANGES */
#define COUNT          (g.ram[A_COUNT])

/* ---- Stack page ---- */
#define A_NGAMES       0x0100  /* # GAMES FOR RANKING */
#define NGAMES         (g.ram[A_NGAMES])
#define A_NPLAYR       0x0101  /* # PLAYERS */
#define NPLAYR         (g.ram[A_NPLAYR])
#define A_BONUS        0x0102  /* BONUS CODE FOR STARTING AT ADVANCED WAVE */
#define BONUS          (g.ram[A_BONUS])
#define A_CURSVL       0x0104  /* CURSOR ACCELERATION DOWN WELL */
#define CURSVL         (g.ram[A_CURSVL])
#define A_CURSVH       0x0105
#define CURSVH         (g.ram[A_CURSVH])
#define A_CURMOD       0x0106  /* CURSOR MODE (-:DROPPING) */
#define CURMOD         (g.ram[A_CURMOD])
#define A_CURSYL       0x0107  /* CURSOR POSITION (FRACTIONAL) */
#define CURSYL         (g.ram[A_CURSYL])
#define A_INMCOU       0x0108  /* # OF INVADERS ON LINES */
#define INMCOU         (g.ram[A_INMCOU])
#define A_INCCOU       0x0109  /* # OF INVADERS CHASING CURSOR */
#define INCCOU         (g.ram[A_INCCOU])
#define A_EXICAM       0x010A  /* INVADER CAN EXIT FLAG */
#define EXICAM         (g.ram[A_EXICAM])
#define A_CAMPC        0x010B  /* INVADER CAM PC */
#define CAMPC          (g.ram[A_CAMPC])
#define A_CAMSTA       0x010C  /* CAM STATUS */
#define CAMSTA         (g.ram[A_CAMSTA])
#define A_BOOMFL       0x010D  /* BOOM ACTIVE FLAG (0=NOT ACTIVE) */
#define BOOMFL         (g.ram[A_BOOMFL])
#define A_BOOMTI       0x010E  /* BOOM TIMER (1/5 SECONDS) */
#define BOOMTI         (g.ram[A_BOOMTI])
#define A_LEVELY       0x010F
#define LEVELY         (g.ram[A_LEVELY])
#define A_WELTYP       0x0111  /* WELL TYPE (0=CLOSED,-1=OPEN) */
#define WELTYP         (g.ram[A_WELTYP])
#define A_WELLID       0x0112  /* WELL CODE */
#define WELLID         (g.ram[A_WELLID])
#define A_ROTFLG       0x0113  /* MSB OF BUILT SUBR BUFFER (IF 0 THEN NOT READY) */
#define ROTFLG         (g.ram[A_ROTFLG])
#define A_ROTDIS       0x0114  /* BUILD WELL REQUEST (NOT 0) */
#define ROTDIS         (g.ram[A_ROTDIS])
#define A_PLAGRO       0x0115  /* STAR FIELD STATUS */
#define PLAGRO         (g.ram[A_PLAGRO])
#define A_EXPCOU       0x0116  /* # OF EXPLOSIONS */
#define EXPCOU         (g.ram[A_EXPCOU])
#define A_COCTAL       0x0117  /* COCKTAIL FLAG */
#define COCTAL         (g.ram[A_COCTAL])
#define A_WCHARIN      0x0118  /* INVADER CHARGE INC/FRAME */
#define WCHARIN        (g.ram[A_WCHARIN])
#define A_WCHARFR      0x0119  /* INVADER CHARGE FREQUENCY (FIRE */
#define WCHARFR        (g.ram[A_WCHARFR])
#define A_WCHAMX       0x011A  /* MAX # OF INVADER CHARGES ON GIRD-1 */
#define WCHAMX         (g.ram[A_WCHAMX])
#define A_QT6          0x011B
#define QT6            (g.ram[A_QT6])
#define A_WINVMX       0x011C  /* MAX # OF INVADERS-1 */
#define WINVMX         (g.ram[A_WINVMX])
#define A_WINVJM       0x011D  /* INVAER JUMP FREQ (JUMP IF */
#define WINVJM         (g.ram[A_WINVJM])
#define A_WNYMMX       0x011E  /* # OF NYMPHS */
#define WNYMMX         (g.ram[A_WNYMMX])
#define A_QT5          0x011F
#define QT5            (g.ram[A_QT5])
#define A_WCHARL       0x0120  /* FRACTION CHARGE INC */
#define WCHARL         (g.ram[A_WCHARL])
#define A_ZADEST       0x0121  /* ZADJL DEST. */
#define ZADEST         (g.ram[A_ZADEST])
#define A_ELICNT       0x0123  /* ENEMY LINE COUNTER (D7=1:WARNING REQUEST) */
#define ELICNT         (g.ram[A_ELICNT])
#define A_BOFLASH      0x0124  /* BONUS FLASH TIMER */
#define BOFLASH        (g.ram[A_BOFLASH])
#define A_SUZTIM       0x0125  /* SUPERZAP TIMER */
#define SUZTIM         (g.ram[A_SUZTIM])
#define A_HIWAVE       0x0126  /* HIGHEST WAVE REACHED IN LAST GAME */
#define HIWAVE         (g.ram[A_HIWAVE])
#define A_HIRATE       0x0127  /* HIGHEST LEVEL-1/2 ALLOWED IN RATE TABLE */
#define HIRATE         (g.ram[A_HIRATE])
#define A_INTIME       0x0128  /* TIME SNCE LAST GAME (13 SECOND UNITS) */
#define INTIME         (g.ram[A_INTIME])
#define A_WFLMIN       0x0129  /* MINIMUM # OF TYPE ON WELL */
#define WFLMIN         (g.ram[A_WFLMIN])
#define A_WPUMIN       0x012A
#define WPUMIN         (g.ram[A_WPUMIN])
#define A_WTAMIN       0x012B
#define WTAMIN         (g.ram[A_WTAMIN])
#define A_WSPMIN       0x012C
#define WSPMIN         (g.ram[A_WSPMIN])
#define A_WFUMIN       0x012D
#define WFUMIN         (g.ram[A_WFUMIN])
#define A_WFLMAX       0x012E  /* MAX # OF TYPE ON WELL */
#define WFLMAX         (g.ram[A_WFLMAX])
#define A_WPUMAX       0x012F
#define WPUMAX         (g.ram[A_WPUMAX])
#define A_WTAMAX       0x0130
#define WTAMAX         (g.ram[A_WTAMAX])
#define A_WSPMAX       0x0131
#define WSPMAX         (g.ram[A_WSPMAX])
#define A_WFUMAX       0x0132
#define WFUMAX         (g.ram[A_WFUMAX])
#define A_SPARE3       0x0133
#define SPARE3         (g.ram[A_SPARE3])
#define A_CHACOU       0x0135  /* # OF CHARGES */
#define CHACOU         (g.ram[A_CHACOU])
#define A_WTFMAX       0x0136  /* TANKER + FLIPPER MAX */
#define WTFMAX         (g.ram[A_WTFMAX])
#define A_SPLINE       0x0139  /* LINEAR SCALE VALUABLE */
#define SPLINE         (g.ram[A_SPLINE])
#define A_SPBINA       0x013A  /* BINARY SCALE VARIABLE */
#define SPBINA         (g.ram[A_SPBINA])
#define A_SPXIND       0x013B  /* INDEX */
#define SPXIND         (g.ram[A_SPXIND])
#define A_SPFTIM       0x013C  /* TIMER */
#define SPFTIM         (g.ram[A_SPFTIM])
#define A_OPFLIP       0x013D  /* OPENINGS FOR EACH TYPE */
#define OPFLIP         (g.ram[A_OPFLIP])
#define A_OPPULS       0x013E
#define OPPULS         (g.ram[A_OPPULS])
#define A_OPTANK       0x013F
#define OPTANK         (g.ram[A_OPTANK])
#define A_OPSPIN       0x0140
#define OPSPIN         (g.ram[A_OPSPIN])
#define A_OPFUSE       0x0141
#define OPFUSE         (g.ram[A_OPFUSE])
#define A_FLIPCO       0x0142
#define FLIPCO         (g.ram[A_FLIPCO])
#define A_PULSCO       0x0143  /* COUNT OF EACH TYPE */
#define PULSCO         (g.ram[A_PULSCO])
#define A_TANKCO       0x0144
#define TANKCO         (g.ram[A_TANKCO])
#define A_SPINCO       0x0145
#define SPINCO         (g.ram[A_SPINCO])
#define A_FUSECO       0x0146
#define FUSECO         (g.ram[A_FUSECO])
#define A_PULTIM       0x0147  /* PULSE TIMER INCREMENT */
#define PULTIM         (g.ram[A_PULTIM])
#define A_PULSON       0x0148  /* PULSE STATUS (MINUS=OFF) */
#define PULSON         (g.ram[A_PULSON])
#define A_WTACAR       0x0149  /* TANK CONTENTS (4 POSSIBILITIES) */
#define WTACAR         (g.ram[A_WTACAR])
#define A_NEARY        0x014D  /* VORTEX LOGO */
#define NEARY          (g.ram[A_NEARY])
#define A_FARY         0x014E
#define FARY           (g.ram[A_FARY])
#define A_NEOFLI       0x014F  /* NYMPHS OFF LIMIT ZONE FLAGS */
#define NEOFLI         (g.ram[A_NEOFLI])
#define A_OLOFLI       0x0150
#define OLOFLI         (g.ram[A_OLOFLI])
#define A_ENSIZE       0x0151  /* COLLISION RANGE FOR EACH INVADER TYPE */
#define ENSIZE         (g.ram[A_ENSIZE])
#define A_BLIFIN       0x0156  /* BONUS LIFE INTERVAL */
#define BLIFIN         (g.ram[A_BLIFIN])
#define A_PULPOT       0x0157  /* HEIGHT AT WHICH PULEARS BECOME POTENT */
#define PULPOT         (g.ram[A_PULPOT])
#define A_LVSGAM       0x0158  /* LIVES/GAME */
#define LVSGAM         (g.ram[A_LVSGAM])
#define A_WFUSCH       0x0159  /* FUSE CHASE PLAYER FLAG (D7 FOR TOP;D6 FOR TUBE) */
#define WFUSCH         (g.ram[A_WFUSCH])
#define A_NWTELI       0x015A  /* NEW WAVE ENEMY LINE HEIGHT */
#define NWTELI         (g.ram[A_NWTELI])
#define A_NWNYMC       0x015B  /* NEW WAVE NYMPH COUNT */
#define NWNYMC         (g.ram[A_NWNYMC])
#define A_WPULCAM      0x015C  /* PULSAR CAM FOR WAVE */
#define WPULCAM        (g.ram[A_WPULCAM])
#define A_WFLICAM      0x015D  /* FLIPPER CAM FOR USAVE */
#define WFLICAM        (g.ram[A_WFLICAM])
#define A_TYPCOD       0x015E
#define TYPCOD         (g.ram[A_TYPCOD])
#define A_WFUFRQ       0x015F  /* FUSE LANE CHANGE PCNT (OF 256.) */
#define WFUFRQ         (g.ram[A_WFUFRQ])
#define A_WINVIL       0x0160  /* INVADER SPEED (FRAC) FOR EACH TYPE */
#define WINVIL         (g.ram[A_WINVIL])
#define A_WFUSIL       0x0164
#define WFUSIL         (g.ram[A_WFUSIL])
#define A_WINVIN       0x0165  /* INVADER SPEED (INT) */
#define WINVIN         (g.ram[A_WINVIN])
#define A_WFUSIH       0x0169
#define WFUSIH         (g.ram[A_WFUSIH])
#define A_OPTIN3       0x016A  /* OPTION SWITCH 3 (BANK OF 4) */
#define OPTIN3         (g.ram[A_OPTIN3])
#define A_PSCALE       0x016B  /* PAUSE SEALER */
#define PSCALE         (g.ram[A_PSCALE])
#define A_QT2          0x016C  /* SECURITY */
#define QT2            (g.ram[A_QT2])
#define A_WPULFI       0x016D  /* PULSAR FIRE FLAG */
#define WPULFI         (g.ram[A_WPULFI])
#define A_SECUVY       0x016E  /* SECURITY COUNTER */
#define SECUVY         (g.ram[A_SECUVY])
#define A_EAZFLG       0x01C6  /* EA ROM ZERO FLAG (NOT 0=ZERO EAROM) */
#define EAZFLG         (g.ram[A_EAZFLG])
#define A_EAREQU       0x01C7  /* EA ROM ACCESS REQUEST */
#define EAREQU         (g.ram[A_EAREQU])
#define A_EARWRQ       0x01C8  /* EA ROM ACCESS TYPE (MATCHES EAREQU) */
#define EARWRQ         (g.ram[A_EARWRQ])
#define A_EABAD        0x01C9  /* EA ROM ACCESS SUCCESS(0) FAIL(1) (MATCHES EAREQU) */
#define EABAD          (g.ram[A_EABAD])
#define A_EAFLG        0x01CA  /* D7=1=ERASE ;=0=R/W */
#define EAFLG          (g.ram[A_EAFLG])
#define A_EABC         0x01CB  /* BYTE INDEX INTO ADDRESS AT EASRCE */
#define EABC           (g.ram[A_EABC])
#define A_EAX          0x01CC  /* BYTE OFFSET INTO EAROM FOR NEXT ACCESS */
#define EAX            (g.ram[A_EAX])
#define A_EACNT        0x01CD  /* BYTE OFFSET INTO EAROM FOR LAST ACCESS */
#define EACNT          (g.ram[A_EACNT])
#define A_EASEL        0x01CE  /* INDEX CODE FOR CURRENT BATCH OPERATION */
#define EASEL          (g.ram[A_EASEL])
#define A_EACS         0x01CF  /* CHECKSUM */
#define EACS           (g.ram[A_EACS])

/* ---- Game RAM ---- */
#define A_CURSL1       0x0200  /* ONE END LINE # */
#define CURSL1         (g.ram[A_CURSL1])
#define A_CURSL2       0x0201  /* OTHER END LINE # (CCW TO CURSL1) */
#define CURSL2         (g.ram[A_CURSL2])
#define A_CURSY        0x0202  /* CURSOR DEPTH */
#define CURSY          (g.ram[A_CURSY])
#define A_NYMPL        0x0203
#define NYMPL          (g.ram[A_NYMPL])
#define A_PARLIX       0x0203  /* FRACTIONAL POSITION */
#define PARLIX         (g.ram[A_PARLIX])
#define A_PARLIY       0x0223
#define PARLIY         (g.ram[A_PARLIY])
#define A_NYMPY        0x0243
#define NYMPY          (g.ram[A_NYMPY])
#define A_PARLIZ       0x0243
#define PARLIZ         (g.ram[A_PARLIZ])
#define A_PARTIX       0x0263  /* INTEGER POSITION (80=CENTER) */
#define PARTIX         (g.ram[A_PARTIX])
#define A_INVAC1       0x0283  /* INVADER STATUS BYTE 1 */
#define INVAC1         (g.ram[A_INVAC1])
#define A_PARTIY       0x0283
#define PARTIY         (g.ram[A_PARTIY])
#define A_INVAC2       0x028A  /* INVADER STATUS BYTE 2 */
#define INVAC2         (g.ram[A_INVAC2])
#define A_INVCAM       0x0291
#define INVCAM         (g.ram[A_INVCAM])
#define A_INVLOO       0x0298
#define INVLOO         (g.ram[A_INVLOO])
#define A_INVAYL       0x029F  /* Y POSITION (FRACTIONAL) */
#define INVAYL         (g.ram[A_INVAYL])
#define A_PARTIZ       0x02A3
#define PARTIZ         (g.ram[A_PARTIZ])
#define A_INVACT       0x02A6  /* TIME SINCE LAST CHARGE LAUNCH */
#define INVACT         (g.ram[A_INVACT])
#define A_CHARL1       0x02AD  /* ONE END LINE # */
#define CHARL1         (g.ram[A_CHARL1])
#define A_INVAL1       0x02B9  /* LINE # FOR 1 LEG (INVADERS) */
#define INVAL1         (g.ram[A_INVAL1])
#define A_CHARL2       0x02C0  /* OTHER END LINE # (CCW TO CHARL1) */
#define CHARL2         (g.ram[A_CHARL2])
#define A_PARLXV       0x02C3  /* FRACTIONAL VELOCITY */
#define PARLXV         (g.ram[A_PARLXV])
#define A_INVAL2       0x02CC  /* LINE # FOR CCW LEG (JUMPS SEG.IF-) */
#define INVAL2         (g.ram[A_INVAL2])
#define A_CHARY        0x02D3  /* Y POSITION (0=INACTIVE) */
#define CHARY          (g.ram[A_CHARY])
#define A_INVAY        0x02DF  /* Y POSITION FOR LEGS (INVADERS) */
#define INVAY          (g.ram[A_INVAY])
#define A_PARLYV       0x02E3
#define PARLYV         (g.ram[A_PARLYV])
#define A_CHARYL       0x02E6  /* Y POSITION FRACTION */
#define CHARYL         (g.ram[A_CHARYL])
#define A_CHARCO       0x02F2  /* CHARGE COLLISION COUNTER */
#define CHARCO         (g.ram[A_CHARCO])
#define A_EXPLOL       0x02FA  /* EXPLOSION LINE # (CW LEG) */
#define EXPLOL         (g.ram[A_EXPLOL])
#define A_EXPLOT       0x0302  /* EXPLOSION TYPE */
#define EXPLOT         (g.ram[A_EXPLOT])
#define A_PARLZV       0x0303
#define PARLZV         (g.ram[A_PARLZV])
#define A_EXPLOY       0x030A  /* EXPLOSION DEPTH (WORLD Y) */
#define EXPLOY         (g.ram[A_EXPLOY])
#define A_EXPLOS       0x0312  /* EXPLOSION SEQUENCES */
#define EXPLOS         (g.ram[A_EXPLOS])
#define A_LINSXH       0x031A  /* NEAR PT. */
#define LINSXH         (g.ram[A_LINSXH])
#define A_PARTXV       0x0323  /* INTEGER VELOCITY (SIGNED) */
#define PARTXV         (g.ram[A_PARTXV])
#define A_LINSXL       0x032A
#define LINSXL         (g.ram[A_LINSXL])
#define A_LINSZH       0x033A
#define LINSZH         (g.ram[A_LINSZH])
#define A_PARTYV       0x0343
#define PARTYV         (g.ram[A_PARTYV])
#define A_LINSZL       0x034A
#define LINSZL         (g.ram[A_LINSZL])
#define A_LIFSXH       0x035A  /* FAR PT. */
#define LIFSXH         (g.ram[A_LIFSXH])
#define A_PARTZV       0x0363
#define PARTZV         (g.ram[A_PARTZV])
#define A_LIFSXL       0x036A
#define LIFSXL         (g.ram[A_LIFSXL])
#define A_LIFSZH       0x037A
#define LIFSZH         (g.ram[A_LIFSZH])
#define A_LIFSZL       0x038A
#define LIFSZL         (g.ram[A_LIFSZL])
#define A_LINSTA       0x039A  /* ENEMY LINE STATUS (D7=1:NEW NEAR PT.;D6=1=SHATTERED) */
#define LINSTA         (g.ram[A_LINSTA])
#define A_ACTIP        0x03AA  /* ACTIVE PLAYER DATA */
#define ACTIP          (g.ram[A_ACTIP])
#define A_SUZCNT       0x03AA  /* SUPERZAPPER USE COUNTER */
#define SUZCNT         (g.ram[A_SUZCNT])
#define A_NYMCOU       0x03AB  /* # OF NYMPHS */
#define NYMCOU         (g.ram[A_NYMCOU])
#define A_LINEY        0x03AC  /* ENEMY LINE HEIGHTS */
#define LINEY          (g.ram[A_LINEY])
#define A_SAVEP        0x03BC  /* STANDBY PLAYER DATA */
#define SAVEP          (g.ram[A_SAVEP])
#define A_SAVEND       0x03CE  /* DUMMY */
#define SAVEND         (g.ram[A_SAVEND])
#define A_LINEX        0x03CE
#define LINEX          (g.ram[A_LINEX])
#define A_LINEZ        0x03DE
#define LINEZ          (g.ram[A_LINEZ])
#define A_LINANG       0x03EE  /* INDEX=ANGLE FROM GRID LINE TO NEXT CCW LINE */
#define LINANG         (g.ram[A_LINANG])
#define A_PLANEY       0x03FE  /* STAR FIELD PLANES */
#define PLANEY         (g.ram[A_PLANEY])
#define A_BOOKKS       0x0406  /* BOOKKEEPING */
#define BOOKKS         (g.ram[A_BOOKKS])
#define A_SECOUL       0x0406  /* GAME UP TIMER */
#define SECOUL         (g.ram[A_SECOUL])
#define A_SECOUM       0x0407
#define SECOUM         (g.ram[A_SECOUM])
#define A_SECOUH       0x0408
#define SECOUH         (g.ram[A_SECOUH])
#define A_SECOPL       0x0409  /* GAME PLAY TIMER */
#define SECOPL         (g.ram[A_SECOPL])
#define A_SECOPM       0x040A
#define SECOPM         (g.ram[A_SECOPM])
#define A_SECOPH       0x040B
#define SECOPH         (g.ram[A_SECOPH])
#define A_NGAMIL       0x040C  /* # OF GAMES */
#define NGAMIL         (g.ram[A_NGAMIL])
#define A_NGAMIH       0x040D
#define NGAMIH         (g.ram[A_NGAMIH])
#define A_NGAME0       0x040E
#define NGAME0         (g.ram[A_NGAME0])
#define A_NGAM2L       0x040F  /* # OF 2 PLAYER GAMES */
#define NGAM2L         (g.ram[A_NGAM2L])
#define A_NGAM2H       0x0410
#define NGAM2H         (g.ram[A_NGAM2H])
#define A_NGAM20       0x0411
#define NGAM20         (g.ram[A_NGAM20])
#define A_BOOKKE       0x0412
#define BOOKKE         (g.ram[A_BOOKKE])
#define A_NGAVGL       0x0412  /* ORIG GAME TIME */
#define NGAVGL         (g.ram[A_NGAVGL])
#define A_NGAVGH       0x0413
#define NGAVGH         (g.ram[A_NGAVGH])
#define A_NGAVGZ       0x0414
#define NGAVGZ         (g.ram[A_NGAVGZ])
#define A_BUFACT       0x0415  /* ACTIVE/AVAILABLE BUFFER */
#define BUFACT         (g.ram[A_BUFACT])
#define A_SPOKST       0x0425  /* SPOKE STATUS (PULEARS) */
#define SPOKST         (g.ram[A_SPOKST])
#define A_LINEXM       0x0435  /* HALF WAY BETWEEN LINES COORDINATES */
#define LINEXM         (g.ram[A_LINEXM])
#define A_LINEZM       0x0445
#define LINEZM         (g.ram[A_LINEZM])
#define A_QT3          0x0455  /* SECURITY */
#define QT3            (g.ram[A_QT3])
#define A_RANKS        0x0600  /* RANK FOR ACH PLAYER(0=NO RANK) */
#define RANKS          (g.ram[A_RANKS])
#define A_TBLIND       0x0602  /* INDEX INTO INITIAL OF NEW INITIAL */
#define TBLIND         (g.ram[A_TBLIND])
#define A_FLGNHI       0x0603  /* FLAG FOR HIS SCORE FOUND */
#define FLGNHI         (g.ram[A_FLGNHI])
#define A_ININDX       0x0604  /* NEW INITIALS LEFT-1 COUNTER */
#define ININDX         (g.ram[A_ININDX])
#define A_TIMHIS       0x0605  /* TIMER UNTIL INITIAL ENTRY IS ABORTED */
#define TIMHIS         (g.ram[A_TIMHIS])
#define A_INITAL       0x0606
#define INITAL         (g.ram[A_INITAL])
#define A_HRANKL       0x061E
#define HRANKL         (g.ram[A_HRANKL])
#define A_HRANKM       0x061F
#define HRANKM         (g.ram[A_HRANKM])
#define A_HRANKH       0x0620
#define HRANKH         (g.ram[A_HRANKH])
#define A_HSCORL       0x0706
#define HSCORL         (g.ram[A_HSCORL])
#define A_HSCORM       0x0707
#define HSCORM         (g.ram[A_HSCORM])
#define A_HSCORH       0x0708
#define HSCORH         (g.ram[A_HSCORH])
#define A_GAMOP1       0x071E  /* GAME PLAY OPTIONS (SWITCH 1) */
#define GAMOP1         (g.ram[A_GAMOP1])
#define A_GAMOP3       0x071F  /* (SWITCH 3) */
#define GAMOP3         (g.ram[A_GAMOP3])
#define A_QT4          0x0720  /* SECURITY */
#define QT4            (g.ram[A_QT4])

/* ---- Vector RAM ---- */
#define A_VECRAM       0x2000  /* VECTOR RAM */
#define A_SWINFO       0x2004
#define A_BAINFO       0x2006
#define A_BBINFO       0x2104
#define A_SWENEL       0x2200
#define A_BAENEL       0x2202
#define A_BBENEL       0x2306
#define A_SWWELL       0x240A
#define A_BAWELL       0x240C
#define A_BBWELL       0x254E
#define A_SWINVA       0x2690
#define A_BAINVA       0x2692
#define A_BBINVA       0x27C8
#define A_SWSHOT       0x28FE
#define A_BASHOT       0x2900
#define A_BBSHOT       0x29AA
#define A_SWNYMP       0x2A54
#define A_BANYMP       0x2A56
#define A_BBNYMP       0x2B96
#define A_SWEXPL       0x2CD6
#define A_BAEXPL       0x2CD8
#define A_BBEXPL       0x2D4A
#define A_SWCURS       0x2DBC
#define A_BACURS       0x2DBE
#define A_BBCURS       0x2DF0
#define A_SWSTAR       0x2E22
#define A_BASTAR       0x2E24
#define A_BBSTAR       0x2EA6
#define A_SCOBUF       0x2F60
#define A_SCLEVEL      0x2FA6
#define A_SCALE        0x2FFC

/* ---- Vector ROM ---- */
#define A_CHAR_0       0x30CA
#define A_CHAR_        0x3168
#define A_VGMSGA       0x31E4  /* ADDRESS OF LETTER ROUTINES */
#define A_HALF         0x325C
#define A_LIFEY        0x326C
#define A_LIFE0        0x327E
#define A_LSYMBL       0x3284
#define A_LSYMB0       0x3286
#define A_INTEST       0x32B6
#define A_HATCH        0x330A
#define A_CHEKER       0x334E
#define A_HYSTER       0x3456
#define A_EASING       0x346E
#define A_COCMSG       0x3482  /* COCKTAIL GAME MESSAGE */
#define A_ROMRPI       0x3492
#define A_BONDRY       0x34A6  /* SCREEN BOUNDARY */
#define A_VORBOX       0x34AA
#define A_EXPL1        0x34C2
#define A_EXPL2        0x34F8
#define A_EXPL3        0x3522
#define A_EXPL4        0x355A
#define A_DIARA2       0x3594
#define A_STAR1        0x3628
#define A_STAR2        0x36DE
#define A_STAR3        0x3780
#define A_STAR4        0x382A
#define A_SPIRA1       0x38CC
#define A_SPIRA2       0x38FA
#define A_SPIRA3       0x3928
#define A_SPIRA4       0x3956
#define A_TANKP        0x3984  /* TANKER OF PULSARS */
#define A_TANKF        0x3996  /* TANKER OF FUSES */
#define A_TANKR        0x39B0
#define A_SPARK1       0x39F4
#define A_SPARK2       0x3A1A
#define A_ESHOT1       0x3A40
#define A_ESHOT2       0x3A72
#define A_ESHOT3       0x3AA2
#define A_ESHOT4       0x3AD4
#define A_SPLAT1       0x3B04
#define A_SPLAT2       0x3B08
#define A_SPLAT3       0x3B0C
#define A_SPLAT4       0x3B10
#define A_SPLAT5       0x3B14
#define A_SPLAT6       0x3B18
#define A_SPLFU1       0x3B84
#define A_SPLFU2       0x3B8A
#define A_SPLFU3       0x3B90
#define A_SPLFU4       0x3B96
#define A_SPLFU5       0x3B9C
#define A_SPLFU6       0x3BA2
#define A_SPLFU7       0x3BA8
#define A_SHRAP        0x3BAE
#define A_FUSE0        0x3C6A
#define A_FUSE1        0x3CB2
#define A_FUSE2        0x3CFC
#define A_FUSE3        0x3D44
#define A_FUSEX1       0x3D8A
#define A_FUSEX2       0x3D96
#define A_FUSEX3       0x3DA4
#define A_JSRDOT       0x3DB2
#define A_SWNORM       0x3DB4
#define A_SWMSGS       0x3DC8
#define A_SWHALT       0x3DCC
#define A_BOKLIT       0x3DCE
#define A_SYSOPT       0x3F16
#define A_VORLIT       0x3F4E
#define A_KILLER       0x3FF2

/* ---- Constants ---- */
#define K_SPACG        0x00
#define K_NHISCO       0x08  /* # OF HIGH SCORES KEPT */
#define K_NRANKS       0x63
#define K_CNEWGA       0x00
#define K_CNEWLI       0x02
#define K_CPLAY        0x04
#define K_CENDLI       0x06
#define K_CENDGA       0x08
#define K_CPAUSE       0x0A
#define K_CNEWAV       0x0C
#define K_CENDWAV      0x0E
#define K_CHISCHK      0x10
#define K_CDLADR       0x14
#define K_CGETINI      0x12
#define K_CNOTFOU      0x14
#define K_CREQRAT      0x16
#define K_CNEWV2       0x18
#define K_CLOGO        0x1A  /* LOGO INIT */
#define K_CINIRAT      0x1C
#define K_CNWLF2       0x1E
#define K_CDROP        0x20  /* DROP MODE */
#define K_CSYSTM       0x22
#define K_CBOOM        0x24  /* BOOM STATE */
#define K_CDPLAY       0x00  /* PLAY */
#define K_CDSYST       0x02  /* SYSTEM CONFIGURATION */
#define K_CDREQRA      0x08  /* REQUEST RANK */
#define K_CDPLPL       0x0E  /* PLAY PLAYER WARNING */
#define K_CDGOVR       0x0C  /* GAME OVER PLAYER MSG */
#define K_CDHITB       0x0A  /* HI SCORE TABLE */
#define K_CDGETI       0x06  /* GET INITIALS */
#define K_CDBOOM       0x04  /* BOOM DISPLAY */
#define K_CDPRST       0x10  /* "PRESS START" */
#define K_CD2GAM       0x16  /* "2 GAME MIN" */
#define K_CDBOXP       0x12  /* LOGO BOX */
#define K_CDLOGP       0x14  /* LOGO ITSELF */
#define K_SECOND       0x14  /* FRAMES/SECOND */
#define K_QUASEC       0x05  /* QUARTER SECOND FACTOR */
#define K_NPARTI       0x10  /* # OF PARTICLES */
#define K_PARLXA       0x20  /* FRACTIONAL */
#define K_PARLYA       0x20
#define K_PARLZA       0x20
#define K_PARTXA       0x00  /* INTEGER (POSITIVE) */
#define K_PARTYA       0x00
#define K_PARTZA       0x00
#define K_LEDOFF       0x03
#define K_NROMS        0x0C
#define K_MCOINR       0x01  /* RIGHT COIN MECH */
#define K_MCOINC       0x02  /* CENTER COIN MECH */
#define K_MCOINL       0x04  /* LEFT COIN MECH */
#define K_S_LMBIT      0x08  /* SLAM */
#define K_MTEST        0x10  /* SELF TEST */
#define K_MDITES       0x20  /* DIAGNOSTIC TEST SWITCH */
#define K_MHALT        0x40  /* VG HALT */
#define K_M3KHTI       0x80  /* 3 KHZ TIMER */
#define K_ROMSTART     0x3000  /* ROM START (VECTOR ROM) */
#define K_MRCCNT       0x01  /* RIGHT COIN COUNTER */
#define K_MMCCNT       0x02  /* CENTER */
#define K_MLCCNT       0x04  /* LEFT */
#define K_MVINVX       0x08  /* VIDEO INVERT X */
#define K_MVINVY       0x10  /* VIDEO INVERT Y */
#define K_MLED1        0x02  /* LED 1 */
#define K_MLED2        0x01  /* LED 2 */
#define K_MFLIP        0x04  /* FLIP (=1 FOR PLAYER 2) */
#define K_MSTRT1       0x20  /* START 1 */
#define K_MSTRT2       0x40  /* START 2 */
#define K_MSUZA        0x08  /* SUPPERZAPPER */
#define K_MFIRE        0x10  /* FIRE */
#define K_MFAKE        0x80  /* FAKE INPUT */
#define K_MOPT13       0x07  /* SPECIAL OPTIONS */
#define K_COCKTA       0x10  /* =1 IF COCKTAIL */
#define K_MOPTI4       0x20  /* SPECIAL OPTION */
#define K_OM2GAM       0x01  /* 2 GAME MIN OPTION MASK */
#define K_BLUE         0x06
#define K_BLULET       0x07
#define K_GREEN        0x05
#define K_RED          0x03
#define K_YELLOW       0x01
#define K_WHITE        0x00
#define K_PURPLE       0x02
#define K_TURQOI       0x04
#define K_WELCOL       0x06  /* WELL */
#define K_CURCOL       0x01  /* CURSOR */
#define K_ICHCOL       0x00  /* ENEMY SHOTS */
#define K_PCHCOL       0x01  /* PLAYER SHOTS */
#define K_INVCOL       0x03  /* INVADERS */
#define K_LETCOL       0x05  /* LETTERS */
#define K_DEPCOL       0x06
#define K_EXPCOL       0x00  /* EXPLOSION */
#define K_FLICOL       0x03  /* FLIPPERS */
#define K_TANCOL       0x02  /* TANKER */
#define K_TRACOL       0x05  /* TRALERS */
#define K_ZAPCOL       0x00  /* SUPER ZAP */
#define K_FRED         0x0C
#define K_FBLUE        0x0B
#define K_FGREEN       0x07
#define K_HRED         0x0D
#define K_ZWHITE       0x00
#define K_ZYELLO       0x04
#define K_ZPURPL       0x08
#define K_ZRED         0x0C
#define K_ZTURQOI      0x03
#define K_ZGREEN       0x07
#define K_ZBLUE        0x0B
#define K_ZBLACK       0x0F
#define K_PSHCTR       0x08  /* PLAYER SOT CENTER */
#define K_PDIWHI       0x09  /* PLAYER DEATH EXPLOSION COLORS */
#define K_PDIYEL       0x0A
#define K_PDIRED       0x0B
#define K_NYMCOL       0x0C  /* NYMPHE */
#define K_FLASH        0x0F  /* CHANGES EVERY 4 MO. */
#define K_MATRACT      0x80  /* D7: 0=ATTRACT 1=GAME */
#define K_MGTMOD       0x40  /* D6:0=NO TIME;START ALLOWED */
#define K_MECHS        0x03
#define K_EMCTRS       0x03
#define K_CBUF1        0x78  /* FOLLOWING BUFFER MAY BE USED FOR OTHER PURPOSES */
#define K_NPLANE       0x08
#define K_NINVAD       0x07
#define K_NLINES       0x10
#define K_NNYMPH       0x40
#define K_NPCHARG      0x08
#define K_NICHARG      0x04
#define K_NCHARG       0x0C
#define K_NEXPLO       0x08
#define K_ILINDDY      0xF0
#define K_ILINLIY      0x10
#define K_INVABI       0x07
#define K_ZABFLI       0x00  /* APPEARANCE:0=FLIPPER */
#define K_ZABPUL       0x01  /* 1=PULSAR */
#define K_ZABTAN       0x02  /* 2=TANKER */
#define K_ZABTRA       0x03  /* 3=TRALER */
#define K_ZABFUS       0x04  /* 4=FUSE */
#define K_INVSEQ       0x18
#define K_INVMOT       0x80
#define K_ZMOTMO       0x00  /* MOTION:0=NOT FLIPPING/LEAPING */
#define K_ZMOTJM       0x80  /* 1=FLIPPER/LEAPING */
#define K_INVROT       0x40
#define K_ZROTCW       0x00  /* ROTATIONAL DIRECTION:0=CW */
#define K_ZROCCW       0x40
#define K_INVCAR       0x03
#define K_ZCARNO       0x00  /* CARRIER (0=NOTHING) */
#define K_ZCARFL       0x01  /* 1=FLIPPERS */
#define K_ZCARPU       0x02  /* 2=PULSARS */
#define K_ZCARFU       0x03  /* 3=FUSES */
#define K_INVFIR       0x40  /* FIREPOWER (0=NO FIRE, 1=FIRE) */
#define K_ZFIRNO       0x00
#define K_ZFIRYE       0x40
#define K_INVDIR       0x80  /* DIRECTION (0=UP, 1=DOWN) */
#define K_ZDIRUP       0x00
#define K_ZDIRDO       0x80
#define K_PCVELO       0x09  /* PLAYER SHOT VELOCITY (I) */
#define K_PULVEL       0xFEA0  /* PULSAR VELOCITY (IF) */
#define K_RATS         0xC0
#define K_MZCOLO       0x08  /* NEW COLOR STAT BIT MASK */
#define K_MZBRIT       0x00  /* NEW INTENSITY STAT BIT */
#define K_DG000        0x2C
#define K_CPSPXI       0xFFFF
#define K_PPSPXI       0x07
#define K_FPSPXI       0x09
#define K_DG0          0xF0
#define K_DI0          0xF0
#define K_DI1          0xB8
#define K_DI2          0x80
#define K_DI3          0x48
#define K_DI4          0x10
#define K_CR0          0xF0
#define K_CR1          0xF0
#define K_CR2          0xB8
#define K_CR3          0xB8
#define K_CR4          0x80
#define K_PX0          0xEC
#define K_PX1          0xD5
#define K_PX2          0xB1
#define K_PX3          0x90
#define K_PZ0          0x94
#define K_PZ1          0xB0
#define K_PZ2          0xB8
#define K_PZ3          0xA7
#define K_CINVA1       0x00
#define K_CNCURS       0x01
#define K_CPULS4       0x09
#define K_CPULS3       0x0A
#define K_CPULS2       0x0B
#define K_CPULS1       0x0C
#define K_CPULS0       0x0D
#define K_EACK         0x01  /* CLOCK BIT */
#define K_EAC1         0x04  /* C1 (INVERTED TO CHIP) */
#define K_EAC2         0x02  /* C2 */
#define K_EACE         0x08  /* CHIP SELECT */
#define K_EAERAS       0x80
#define K_EAWRIT       0x40
#define K_EAREAD       0x20
#define K_QCHKS2       0x4D
#define K_QCHKS3       0x16
#define K_QCHKS4       0xAB
#define K_QCHKS5       0xE1
#define K_QCHKS6       0x1D
#define K_QCHKS7       0x3E
#define K_QCHKS8       0xDB
#define K_QCHKS9       0x00
#define K_QCHKSA       0x7C
#define K_QCHKSB       0x73
#define K_MGAMOV       0x00  /* GAME OVER */
#define K_MPLAYR       0x02  /* PLAYER (BIG) */
#define K_MPLYR2       0x04  /* PLAYER (NORMAL) */
#define K_MPRESS       0x06  /* PRESS START */
#define K_MPLAY        0x08  /* PLAY */
#define K_MENTER       0x0A  /* ENTER */
#define K_MPRMOV       0x0C  /* SPIN */
#define K_MPRFIR       0x0E  /* PRESS FIRE */
#define K_MHIGHS       0x10  /* HIGH SCORE */
#define K_MRANK        0x12  /* RANK */
#define K_MRATE        0x14  /* RATE YOURSELF */
#define K_MNOVIC       0x16  /* NOVICE */
#define K_MEXPER       0x18  /* EXPERT */
#define K_MBONUS       0x1A  /* BONUS */
#define K_MTIME        0x1C  /* TIME */
#define K_MLEVEL       0x1E  /* LEVEL */
#define K_MHOLE        0x20  /* HOLE */
#define K_MINSER       0x22  /* INSERT COINS */
#define K_MCMODE       0x24  /* FREE PLAY */
#define K_MCMOD1       0x26  /* 1 COIN 2 PLAYS */
#define K_MCMOD2       0x28  /* 1 COIN 1 PLAY */
#define K_MCMOD3       0x2A  /* 2 COINS 1 PLAY */
#define K_MATARI       0x2C  /* MCMLXXX ATARI */
#define K_MCREDI       0x2E  /* CREDITS */
#define K_MBONPT       0x30  /* BONUS PTS */
#define K_M2GAME       0x32  /* 2 GAME MINIMUM */
#define K_MBOLIF       0x34  /* BONUS EVERY */
#define K_MSPIKE       0x36  /* AVOID SPIKES */
#define K_MAPROA       0x38  /* APPROACH */
#define K_MSUPZA       0x3A  /* NEW SUPER */
#define K_ZATLIC       0x10
#define K_ITIMHI       0x60
#define K_CBLANK       0x1A
#define K_ZATC4C       0x0A
#define K_FARINC       0x08
#define K_NCHANL       0x10
#define K_STVAL        0x00  /* VALUE TO START SEQUENCE */
#define K_FRCNT        0x01  /* # OF FRAMES BEFORE ANY CHANGE */
#define K_CHANGE       0x02  /* AMOUNT OF CHANGE */
#define K_NUMBER       0x03  /* TOTAL NUMBER OF CHANGES IN THIS SEQUENCE */
#define K_SIDLO        0x0F  /* CURSOR MOVES */
#define K_SIDEX        0x1F  /* ENEMY EXPLOSION */
#define K_SIDLA        0x2F  /* PLAYER FIRE */
#define K_SIDPU        0x3F  /* PULSATION */
#define K_SIDWP        0x4F  /* SPECIAL SCORE */
#define K_SIDDI        0x5F  /* PLAYER DIES */
#define K_SIDT2        0x6F  /* THRUST IN TUBE */
#define K_SIDT3        0x7F  /* THRUST IN SPACE */
#define K_SIDES        0x8F  /* ENEMY SHOT */
#define K_SIDEL        0x9F  /* ENEMY LINE DESTRUCTION */
#define K_SIDSL        0xAF  /* SLAM */
#define K_SIDS3        0xBF  /* 3 SECONDS LEFT WARNING */
#define K_SIDPO        0xCF  /* PULSAR OFF */
#define K_AUDCV        0x00
#define K_AUDCV2       0x00
#define K_MBCOND       0x78
#define K_RAMCND       0x79
#define K_PK1CND       0x7A
#define K_PK2CND       0x7B
#define K_EARCND       0x7C
#define K_CHKSMS       0x7D
#define K_BCINFO       0x00
#define K_BCENEL       0x01
#define K_BCWELL       0x02
#define K_BCINVA       0x03
#define K_BCSHOT       0x04
#define K_BCNYMP       0x05
#define K_BCEXPL       0x06
#define K_BCCURS       0x07
#define K_BCSTAR       0x08
#define K_PTEXP1       0x00  /* EXPLOSION 1 SMALLEST */
#define K_PTCURS       0x08  /* DIAMON DOTS RADIUS 2 */
#define K_PTSTR1       0x0A  /* STAR FIELD 1 */
#define K_PTSPI1       0x12  /* SPIRALS */
#define K_PTTANK       0x1A  /* TANKER */
#define K_PTSPAR       0x1C  /* SPARKLE */
#define K_PTESHO       0x20  /* ENEMY SHOT */
#define K_PTSPLA       0x28  /* SMALL SPLAT */
#define K_PTTANP       0x4A  /* PULSAR TANKER */
#define K_PTTANF       0x4C  /* FUSE TANKER */
#define K_PTFUSE       0x4E  /* FUSE */
#define K_PTFUSX       0x56  /* FUSE EXPLOSION */
#define K_T1           0x02  /* 1 BYTE IN PARAMETER FIELD GOES FOR ALL WAVES IN RANGE */
#define K_TZ           0x04  /* 1 BYTE IN PARAMETER FIELD FOR EACH WAVE IN RANGE */
#define K_TE           0x00  /* EOT (RETURN WITH 0) */
#define K_TZANDF       0x06  /* AND CURRENT WAVE WITH F, THE DO TZ */
#define K_TA           0x08  /* AND BYTE 4 TO BYTE 3 FOR EACH LEVEL */
#define K_TB           0x0A  /* ADD BYTE 3 TO WINVIN */
#define K_TR           0x0C  /* ALTERNATE BETWEEN BYTES 3 & 4 */
#define K_ZEASY        0x01
#define K_ZHARD        0x02
#define K_PN           0x28
#define K_PC           0x14
#define K_IPTYPE       0x05  /* EXPLOSION TYPE CODES */
#define K_CPTYPE       0x01
#define K_CCTYPE       0x00
#define K_CITYPE       0x00
#define K_CFTYPE       0x02
#define K_CSUMAX       0x02
#define K_CSUINT       0x01
#define K_CSUSTA       0x03

#endif /* STATE_DEFS_H */
