/* vecrom.h - GENERATED by c_src/tools/gen_roms.py - do not edit. */
#ifndef VECROM_H
#define VECROM_H
#include <stdint.h>
#define VECROM_BASE 0x3000
#define VECROM_SIZE 0x1000
extern const uint8_t vecrom[0x1000]; /* vector ROM */
#endif
